/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { PresetPageButton } from './preset';
export {
	STYLIST_MENU_ATOMIC_TAB_ITEMS,
	STYLIST_MENU_FUNCTIONAL_PRIMARY_SECTIONS,
	STYLIST_MENU_FUNCTIONAL_TAB_ITEMS,
	STYLIST_MENU_MENU_ITEMS
} from './record';
