/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export {
	BREADCRUMB_TEMPLATE,
	PresetDropdownMenu,
	PresetPageButton
} from './preset';
export {
	ACCORDION_CONTEXT_DEFAULT,
	SIDE_BY_SIDE_ALIGN_CLASSES,
	SIDE_BY_SIDE_GAP_CLASSES,
	SIDE_BY_SIDE_JUSTIFY_CLASSES,
	SIDE_BY_SIDE_SECTION_WIDTH_MOBILE,
	SIDE_BY_SIDE_SECTION_WIDTH_RESPONSIVE,
	STYLIST_MENU_ATOMIC_TAB_ITEMS,
	STYLIST_MENU_FUNCTIONAL_PRIMARY_SECTIONS,
	STYLIST_MENU_FUNCTIONAL_TAB_ITEMS,
	STYLIST_MENU_MENU_ITEMS,
	STYLIST_TAB_DEFAULT_ITEMS,
	TAB_CONTEXT,
	TAB_PANEL_CONTEXT
} from './record';
export {
	BURGER_MENU_ARIA_LABEL,
	SLASH_ICON
} from './value';
export type { AccordionContext } from './record';
