/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { TOKEN_COMMUNICATION_ICON, TOKEN_MESSAGE_STATE, TOKEN_MESSAGE_STATUS, TOKEN_NOTIFICATION_CHANNEL } from './enum';
export { CHAT_ROOM_VARIANT_CLASSES, DEFAULT_CHAT_HEADER, MESSAGE_BUBBLE_VARIANT_CLASSES, PRESET_CHAT_HEADER, PRESET_MESSAGE_TIMESTAMP, USER_STATUS_TEXT } from './map';
export { MESSAGE_AVATAR_SIZE_CLASSES } from './record';
export { CHAT_PREVIEW_ICON_CHECK, CHAT_PREVIEW_ICON_CHECK_CHECK, MESSAGE_STATUS_ICONS } from './struct';