/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { TOKEN_MESSAGE_STATE, TOKEN_MESSAGE_STATUS, TOKEN_NOTIFICATION_CHANNEL } from './enum';
export { DEFAULT_CHAT_HEADER, PRESET_CHAT_HEADER, PRESET_MESSAGE_TIMESTAMP } from './map';
export { MESSAGE_AVATAR_SIZE_CLASSES } from './record';