export const TOKEN_MEDIA_ICON = [
	'audio-player',
	'audio-slider',
	'audio-visualizer',
	'avatar',
	'avatar-group',
	'blur',
	'box',
	'components',
	'favicon',
	'icon',
	'icons',
	'image',
	'image-gallery',
	'image-with-caption',
	'media',
	'media-library',
	'models',
	'node-icon',
	'picture-toolbar',
	'video-player'
] as const;
