export const TOKEN_NAVIGATION_ICON = [
	'accordion',
	'accordion-molecule',
	'arrow-down',
	'arrow-up',
	'breadcrumb',
	'breadcrumb-link',
	'breadcrumb-separator',
	'breadcrumbs',
	'chevron-down',
	'chevron-up',
	'dialogs',
	'general-toolbar',
	'menu',
	'menus-molecule',
	'navigation',
	'pagination',
	'panels',
	'side-by-side-layout',
	'sidebar',
	'stepper',
	'toolbars-molecule'
] as const;
