export const TOKEN_COMMERCE_ICON = [
	'billing-summary',
	'bulk-order-form',
	'cards',
	'cart-summary',
	'checkout-form',
	'commerce',
	'contracts',
	'currency-converter',
	'discount-applier',
	'inventory-tracker',
	'order-confirmation',
	'order-history',
	'order-tracking',
	'payment',
	'prices',
	'product',
	'products',
	'quote-request',
	'return-policy',
	'rfqform',
	'shipping-calculator',
	'shipping-info',
	'subscription-manager',
	'tax-calculator',
	'upsell',
	'warranty-info'
] as const;
