import type { FileType } from '$stylist/file/type/object/common/file-type';
import type { ComputeIntersectAll } from '$stylist/theme/type/compute/intersect-all';
export interface RecipeFileListItem {
	item: ({
id: string;
	name: string;
	type: FileType;
	size?: number;
	modified?: Date;
	created?: Date;
	path?: string;
	thumbnail?: string;
	permissions?: string;
	owner?: string;
	icon?: string;
	selected?: boolean;
});
	class?: string;
	cellClass?: string;
	onItemSelect?: (item: ({
id: string;
	name: string;
	type: FileType;
	size?: number;
	modified?: Date;
	created?: Date;
	path?: string;
	thumbnail?: string;
	permissions?: string;
	owner?: string;
	icon?: string;
	selected?: boolean;
})) => void;
	onItemDoubleClick?: (item: ({
id: string;
	name: string;
	type: FileType;
	size?: number;
	modified?: Date;
	created?: Date;
	path?: string;
	thumbnail?: string;
	permissions?: string;
	owner?: string;
	icon?: string;
	selected?: boolean;
})) => void;
	onItemAction?: (item: ({
id: string;
	name: string;
	type: FileType;
	size?: number;
	modified?: Date;
	created?: Date;
	path?: string;
	thumbnail?: string;
	permissions?: string;
	owner?: string;
	icon?: string;
	selected?: boolean;
}), action: string) => void;
	showThumbnail?: boolean;
	showSize?: boolean;
	showModified?: boolean;
	showOwner?: boolean;
	enableSelection?: boolean;
	disabled?: boolean;
	variant?: 'default' | 'compact';
	[key: string]: unknown;
}
