import type { IABTestConfiguratorProps } from '$stylist/information/interface/abtest-configurator';
import type { AccessibilityCheckboxProps } from '$stylist/information/interface/accessibility-checkbox';
import type { IAiResultCardProps } from '$stylist/information/interface/ai-result-card';
import type { IAlertCardProps } from '$stylist/information/interface/alert-card';
import type { AnimatedNumberProps, NumberFlowProps } from '$stylist/information/interface/animation';
import type { AtomicPrinciplesProps } from '$stylist/information/interface/atomic-principles';
import type { AuthGuardProps } from '$stylist/information/interface/auth-guard';
import type { AutoCompleteProps } from '$stylist/information/interface/auto-complete';
import type { BackgroundProps } from '$stylist/information/interface/background';
import type { IBaseCardElementProps } from '$stylist/information/interface/base-card';
import type { IBillingSummaryProps } from '$stylist/information/interface/billing-summary';
import type { BlockquoteProps } from '$stylist/information/interface/blockquote';
import type { BorderProps } from '$stylist/information/interface/border';
import type { CanvasChartProps } from '$stylist/information/interface/canvas-chart';
import type { CanvasImageEditorProps } from '$stylist/information/interface/canvas-image-editor';
import type { ICategoryCardProps } from '$stylist/information/interface/category-card';
import type { CommentSystemProps } from '$stylist/information/interface/comment-system';
import type { CommentThreadProps } from '$stylist/information/interface/comment-thread';
import type { IComparisonCardProps } from '$stylist/information/interface/comparison-card';
import type { ConnectionLineProps } from '$stylist/information/interface/connection-line';
import type { CountryFlagProps } from '$stylist/information/interface/countryflag';
import type { IDownloadCardProps } from '$stylist/information/interface/download-card';
import type { IEventCalendarProps } from '$stylist/information/interface/event-calendar';
import type { IExpandableCardProps } from '$stylist/information/interface/expandable-card';
import type { IGeoJSONViewerProps } from '$stylist/information/interface/geo-jsonviewer';
import type { GraphCanvasProps } from '$stylist/information/interface/graph-canvas';
import type { GraphEdgeProps, GraphNodeProps } from '$stylist/information/interface/graph';
import type { GraphNodeCardProps } from '$stylist/information/interface/graph-node-card';
import type { GraphPortProps } from '$stylist/information/interface/graph-port';
import type { GraphToolbarProps } from '$stylist/information/interface/graph-toolbar';
import type { IImageGalleryProps } from '$stylist/information/interface/image-gallery';
import type { IKPIIndicatorProps } from '$stylist/information/interface/kpiindicator';
import type { LabelProps } from '$stylist/information/interface/label';
import type { ILinkCardProps } from '$stylist/information/interface/link-card';
import type { LiteGraphNodeProps } from '$stylist/information/interface/litegraph-node';
import type { IMapMarkerProps } from '$stylist/information/interface/map-marker';
import type { IMessageBubbleProps } from '$stylist/information/interface/message-bubble';
import type { IMessageComposerProps } from '$stylist/information/interface/message-composer';
import type { IMessageMetaProps } from '$stylist/information/interface/message-meta';
import type { IMetricCardProps } from '$stylist/information/interface/metric-card';
import type { NodeHeaderProps } from '$stylist/information/interface/node-header';
import type { NodePropertiesPanelProps } from '$stylist/information/interface/node-properties-panel';
import type { NodePropertyProps } from '$stylist/information/interface/node-property';
import type { NodeTitleProps } from '$stylist/information/interface/node-title';
import type {
	NotificationCenterProps,
	NotificationListProps,
	NotificationPreferencesProps,
	ScheduledNotificationProps
} from '$stylist/information/interface/notifications';
import type { IOrderConfirmationProps } from '$stylist/information/interface/order-confirmation';
import type { PageEllipsisProps } from '$stylist/information/interface/page-ellipsis';
import type { PortGroupProps } from '$stylist/information/interface/port-group';
import type { PredictionResultProps } from '$stylist/information/interface/prediction-result';
import type { IPriceAlertElementProps } from '$stylist/information/interface/price-alert';
import type { IProductSortingProps } from '$stylist/information/interface/product-sorting';
import type { PromptBuilderProps } from '$stylist/information/interface/prompt-builder';
import type { QuoteRequestProps } from '$stylist/information/interface/quote-request';
import type { ScatterPlotProps } from '$stylist/information/interface/scatter-plot';
import type { IScheduleCalendarProps } from '$stylist/information/interface/schedule-calendar';
import type { SearchResultsProps } from '$stylist/information/interface/search-results';
import type { SentimentAnalysisProps } from '$stylist/information/interface/sentiment-analysis';
import type { SortableGridProps } from '$stylist/information/interface/sortable-grid';
import type { IStatCardProps } from '$stylist/information/interface/stat-card';
import type { StatusDashboardProps } from '$stylist/information/interface/status-dashboard';
import type { TableProps } from '$stylist/information/interface/table';
import type { ITeamMemberCardProps } from '$stylist/information/interface/team-member-card';
import type { TooltipWithArrowProps } from '$stylist/information/interface/tooltip-with-arrow';

export interface MapInformationContract {
	ABTestConfigurator: IABTestConfiguratorProps;
	AccessibilityCheckbox: AccessibilityCheckboxProps;
	AiResultCard: IAiResultCardProps;
	AlertCard: IAlertCardProps;
	AnimatedNumber: AnimatedNumberProps;
	NumberFlow: NumberFlowProps;
	AtomicPrinciples: AtomicPrinciplesProps;
	AuthGuard: AuthGuardProps;
	AutoComplete: AutoCompleteProps;
	Background: BackgroundProps;
	BaseCard: IBaseCardElementProps;
	BillingSummary: IBillingSummaryProps;
	Blockquote: BlockquoteProps;
	Border: BorderProps;
	CanvasChart: CanvasChartProps;
	CanvasImageEditor: CanvasImageEditorProps;
	CategoryCard: ICategoryCardProps;
	CommentSystem: CommentSystemProps;
	CommentThread: CommentThreadProps;
	ComparisonCard: IComparisonCardProps;
	ConnectionLine: ConnectionLineProps;
	CountryFlag: CountryFlagProps;
	DownloadCard: IDownloadCardProps;
	EventCalendar: IEventCalendarProps;
	ExpandableCard: IExpandableCardProps;
	GeoJSONViewer: IGeoJSONViewerProps;
	GraphCanvas: GraphCanvasProps;
	GraphEdge: GraphEdgeProps;
	GraphNode: GraphNodeProps;
	GraphNodeCard: GraphNodeCardProps;
	GraphPort: GraphPortProps;
	GraphToolbar: GraphToolbarProps;
	ImageGallery: IImageGalleryProps;
	KPIIndicator: IKPIIndicatorProps;
	Label: LabelProps;
	LinkCard: ILinkCardProps;
	LiteGraphNode: LiteGraphNodeProps;
	MapMarker: IMapMarkerProps;
	MessageBubble: IMessageBubbleProps;
	MessageComposer: IMessageComposerProps;
	MessageMeta: IMessageMetaProps;
	MetricCard: IMetricCardProps;
	NodeHeader: NodeHeaderProps;
	NodePropertiesPanel: NodePropertiesPanelProps;
	NodeProperty: NodePropertyProps;
	NodeTitle: NodeTitleProps;
	NotificationCenter: NotificationCenterProps;
	NotificationList: NotificationListProps;
	NotificationPreferences: NotificationPreferencesProps;
	OrderConfirmation: IOrderConfirmationProps;
	PageEllipsis: PageEllipsisProps;
	PortGroup: PortGroupProps;
	PredictionResult: PredictionResultProps;
	PriceAlert: IPriceAlertElementProps;
	ProductSorting: IProductSortingProps;
	PromptBuilder: PromptBuilderProps;
	QuoteRequest: QuoteRequestProps;
	ScatterPlot: ScatterPlotProps;
	ScheduleCalendar: IScheduleCalendarProps;
	SearchResults: SearchResultsProps;
	SentimentAnalysis: SentimentAnalysisProps;
	ScheduledNotification: ScheduledNotificationProps;
	SortableGrid: SortableGridProps;
	StatCard: IStatCardProps;
	StatusDashboard: StatusDashboardProps;
	Table: TableProps;
	TeamMemberCard: ITeamMemberCardProps;
	TooltipWithArrow: TooltipWithArrowProps;
}