import type { SlotABTestConfigurator as IABTestConfiguratorProps } from '$stylist/marketing/interface/slot/ab-test-configurator';
import type { AccessibilityCheckboxRecipe as AccessibilityCheckboxProps } from '$stylist/information/interface/recipe/accessibility-checkbox';
import type { SlotAiResultCard as IAiResultCardProps } from '$stylist/science/interface/slot/ai-result-card';
import type { AlertCardRecipe as IAlertCardProps } from '$stylist/commerce/interface/recipe/alert-card';
import type { AnimatedNumberRecipe as AnimatedNumberProps } from '$stylist/typography/interface/recipe/animated-number';
import type { NumberFlowRecipe as NumberFlowProps } from '$stylist/typography/interface/recipe/number-flow';
import type { AtomicPrinciplesRecipe as AtomicPrinciplesProps } from '$stylist/information/interface/recipe/atomic-principles';
import type { AuthGuardRecipe as AuthGuardProps } from '$stylist/management/interface/recipe/auth-guard';
import type { AutoCompleteRecipe as AutoCompleteProps } from '$stylist/input/interface/recipe/auto-complete';
import type { ThemeBackgroundRecipe } from '$stylist/layout/interface/recipe/background';
import type { BaseCardRecipe as IBaseCardElementProps } from '$stylist/commerce/interface/recipe/base-card';
import type { SlotBillingSummary as IBillingSummaryProps } from '$stylist/commerce/interface/slot/billing-summary';
import type { BlockquoteRecipe as BlockquoteProps } from '$stylist/typography/interface/recipe/blockquote';
import type { BorderRecipe } from '$stylist/layout/interface/recipe/border';
import type { CanvasChartRecipe as CanvasChartProps } from '$stylist/chart/interface/recipe/canvas-chart';
import type { CanvasImageEditorRecipe as CanvasImageEditorProps } from '$stylist/canvas/interface/recipe/canvas-image-editor';
import type { CategoryCardRecipe as ICategoryCardProps } from '$stylist/commerce/interface/recipe/category-card';
import type { SlotCommentSystem as CommentSystemProps } from '$stylist/social/interface/slot/comment-system';
import type { SlotCommentThread as CommentThreadProps } from '$stylist/social/interface/slot/comment-thread';
import type { ComparisonCardRecipe as IComparisonCardProps } from '$stylist/commerce/interface/recipe/comparison-card';
import type { ConnectionLineRecipe as ConnectionLineProps } from '$stylist/science/interface/recipe/connection-line';
import type { CountryFlagRecipe as CountryFlagProps } from '$stylist/geo/interface/recipe/country-flag';
import type { SlotDownloadCard as IDownloadCardProps } from '$stylist/file/interface/slot/download-card';
import type { SlotEventCalendar as IEventCalendarProps } from '$stylist/calendar/interface/slot/event-calendar';
import type { ExpandableCardRecipe } from '$stylist/commerce/interface/recipe/expandable-card';
import type { SlotGeoJSONViewer as IGeoJSONViewerProps } from '$stylist/geo/interface/slot/geo-json-viewer';
import type { GraphCanvasRecipe as GraphCanvasProps } from '$stylist/science/interface/recipe/graph-canvas';
import type { GraphEdgeRecipe } from '$stylist/science/interface/recipe/graph-edge';
import type { GraphNodeRecipe } from '$stylist/science/interface/recipe/graph-node';
import type { GraphNodeCardRecipe as GraphNodeCardProps } from '$stylist/commerce/interface/recipe/graph-node-card';
import type { GraphPortRecipe as GraphPortProps } from '$stylist/science/interface/recipe/graph-port';
import type { GraphToolbarRecipe as GraphToolbarProps } from '$stylist/science/interface/recipe/graph-toolbar';
import type { ContractImageGallery as IImageGalleryProps } from '$stylist/media/interface/contract/image-gallery';
import type { KPIIndicatorRecipe } from '$stylist/typography/interface/recipe/kpi-indicator';
import type { LabelRecipe as LabelProps } from '$stylist/typography/interface/recipe/label';
import type { LinkCardRecipe } from '$stylist/commerce/interface/recipe/link-card';
import type { LiteGraphNodeProps } from '$stylist/science/type/struct/lite-graph-node-props';
import type { SlotMapMarker as IMapMarkerProps } from '$stylist/geo/interface/slot/map-marker';
import type { SlotMessageBubble as IMessageBubbleProps } from '$stylist/communication/interface/slot/message-bubble';
import type { SlotMessageComposer as IMessageComposerProps } from '$stylist/communication/interface/slot/message-composer';
import type { SlotMessageMeta as IMessageMetaProps } from '$stylist/communication/interface/slot/message-meta';
import type { MetricCardRecipe as IMetricCardProps } from '$stylist/commerce/interface/recipe/metric-card';
import type { NodeHeaderRecipe as NodeHeaderProps } from '$stylist/science/interface/recipe/node-header';
import type { NodePropertiesPanelRecipe as NodePropertiesPanelProps } from '$stylist/science/interface/recipe/node-properties-panel';
import type { NodePropertyRecipe as NodePropertyProps } from '$stylist/science/interface/recipe/node-property';
import type { NodeTitleRecipe as NodeTitleProps } from '$stylist/science/interface/recipe/node-title';
import type { NotificationCenterProps } from '$stylist/communication/type/struct/notification-center-props';
import type { NotificationListProps } from '$stylist/communication/type/struct/notification-list-props';
import type { NotificationPreferencesProps } from '$stylist/communication/type/struct/notification-preferences-props';
import type { ScheduledNotificationProps } from '$stylist/communication/type/struct/scheduled-notification-props';
import type { SlotOrderConfirmation as IOrderConfirmationProps } from '$stylist/commerce/interface/slot/order-confirmation';
import type { PageEllipsisRecipe as PageEllipsisProps } from '$stylist/navigation/interface/recipe/page-ellipsis';
import type { PortGroupRecipe as PortGroupProps } from '$stylist/media/interface/recipe/port-group';
import type { SlotPredictionResult as PredictionResultProps } from '$stylist/science/interface/slot/prediction-result';
import type { SlotPriceAlertElement as IPriceAlertElementProps } from '$stylist/commerce/interface/slot/price-alert-element';
import type { SlotProductSorting as IProductSortingProps } from '$stylist/commerce/interface/slot/product-sorting';
import type { SlotPromptBuilder as PromptBuilderProps } from '$stylist/science/interface/slot/prompt-builder';
import type { RecipeQuoteRequest as QuoteRequestProps } from '$stylist/commerce/interface/recipe/quote-request';
import type { ScatterPlotRecipe } from '$stylist/chart/interface/recipe/scatter-plot';
import type { SlotScheduleCalendar as IScheduleCalendarProps } from '$stylist/calendar/interface/slot/schedule-calendar';
import type { SearchResultsRecipe as SearchResultsProps } from '$stylist/information/interface/recipe/search-results';
import type { SlotSentimentAnalysis as SentimentAnalysisProps } from '$stylist/science/interface/slot/sentiment-analysis';
import type { SortableGridRecipe as SortableGridProps } from '$stylist/information/interface/recipe/sortable-grid';
import type { StatsCardRecipe as StatCardRecipe } from '$stylist/information/interface/recipe/stats-card';
import type { StatusDashboardRecipe } from '$stylist/management/interface/recipe/status-dashboard';
import type { TableRecipe } from '$stylist/information/interface/recipe/table';
import type { SlotTeamMemberCard as ITeamMemberCardProps } from '$stylist/management/interface/slot/team-member-card';
import type { TooltipWithArrowRecipe as TooltipWithArrowProps } from '$stylist/navigation/interface/recipe/tooltip-with-arrow';
import type { SlotEventCalendar } from '$stylist/calendar/interface/slot/event-calendar';
import type { SlotScheduleCalendar } from '$stylist/calendar/interface/slot/schedule-calendar';
import type { SlotBillingSummary } from '$stylist/commerce/interface/slot/billing-summary';
import type { SlotOrderConfirmation } from '$stylist/commerce/interface/slot/order-confirmation';
import type { SlotPriceAlertElement } from '$stylist/commerce/interface/slot/price-alert-element';
import type { SlotProductSorting } from '$stylist/commerce/interface/slot/product-sorting';
import type { SlotMessageBubble } from '$stylist/communication/interface/slot/message-bubble';
import type { SlotMessageComposer } from '$stylist/communication/interface/slot/message-composer';
import type { SlotMessageMeta } from '$stylist/communication/interface/slot/message-meta';
import type { SlotDownloadCard } from '$stylist/file/interface/slot/download-card';
import type { SlotGeoJSONViewer } from '$stylist/geo/interface/slot/geo-json-viewer';
import type { SlotMapMarker } from '$stylist/geo/interface/slot/map-marker';
import type { SlotAutoComplete } from '$stylist/input/interface/slot/auto-complete';
import type { SlotTeamMemberCard } from '$stylist/management/interface/slot/team-member-card';
import type { SlotABTestConfigurator } from '$stylist/marketing/interface/slot/ab-test-configurator';
import type { SlotAiResultCard } from '$stylist/science/interface/slot/ai-result-card';
import type { SlotPredictionResult } from '$stylist/science/interface/slot/prediction-result';
import type { SlotPromptBuilder } from '$stylist/science/interface/slot/prompt-builder';
import type { SlotSentimentAnalysis } from '$stylist/science/interface/slot/sentiment-analysis';
import type { SlotCommentSystem } from '$stylist/social/interface/slot/comment-system';
import type { SlotCommentThread } from '$stylist/social/interface/slot/comment-thread';

export interface ContractMapInformation {
	ABTestConfigurator: SlotABTestConfigurator;
	AccessibilityCheckbox: AccessibilityCheckboxProps;
	AiResultCard: SlotAiResultCard;
	AlertCard: IAlertCardProps;
	AnimatedNumber: AnimatedNumberProps;
	NumberFlow: NumberFlowProps;
	AtomicPrinciples: AtomicPrinciplesProps;
	AuthGuard: AuthGuardProps;
	AutoComplete: SlotAutoComplete;
	Background: ThemeBackgroundRecipe;
	BaseCard: IBaseCardElementProps;
	BillingSummary: SlotBillingSummary;
	Blockquote: BlockquoteProps;
	Border: BorderRecipe;
	CanvasChart: CanvasChartProps;
	CanvasImageEditor: CanvasImageEditorProps;
	CategoryCard: ICategoryCardProps;
	CommentSystem: SlotCommentSystem;
	CommentThread: SlotCommentThread;
	ComparisonCard: IComparisonCardProps;
	ConnectionLine: ConnectionLineProps;
	CountryFlag: CountryFlagProps;
	DownloadCard: SlotDownloadCard;
	EventCalendar: SlotEventCalendar;
	ExpandableCard: ExpandableCardRecipe;
	GeoJSONViewer: SlotGeoJSONViewer;
	GraphCanvas: GraphCanvasProps;
	SlotGraphEdge: GraphEdgeRecipe;
	SlotGraphNode: GraphNodeRecipe;
	GraphNodeCard: GraphNodeCardProps;
	GraphPort: GraphPortProps;
	GraphToolbar: GraphToolbarProps;
	ImageGallery: IImageGalleryProps;
	KPIIndicator: KPIIndicatorRecipe;
	Label: LabelProps;
	LinkCard: LinkCardRecipe;
	LiteGraphNode: LiteGraphNodeProps;
	MapMarker: SlotMapMarker;
	MessageBubble: SlotMessageBubble;
	MessageComposer: SlotMessageComposer;
	MessageMeta: SlotMessageMeta;
	MetricCard: IMetricCardProps;
	NodeHeader: NodeHeaderProps;
	NodePropertiesPanel: NodePropertiesPanelProps;
	NodeProperty: NodePropertyProps;
	NodeTitle: NodeTitleProps;
	NotificationCenter: NotificationCenterProps;
	NotificationList: NotificationListProps;
	NotificationPreferences: NotificationPreferencesProps;
	OrderConfirmation: SlotOrderConfirmation;
	PageEllipsis: PageEllipsisProps;
	PortGroup: PortGroupProps;
	PredictionResult: SlotPredictionResult;
	PriceAlert: SlotPriceAlertElement;
	ProductSorting: SlotProductSorting;
	PromptBuilder: SlotPromptBuilder;
	RecipeQuoteRequest: QuoteRequestProps;
	ScatterPlot: ScatterPlotRecipe;
	ScheduleCalendar: SlotScheduleCalendar;
	SearchResults: SearchResultsProps;
	SentimentAnalysis: SlotSentimentAnalysis;
	ScheduledNotification: ScheduledNotificationProps;
	SortableGrid: SortableGridProps;
	StatCard: StatCardRecipe;
	StatusDashboard: StatusDashboardRecipe;
	Table: TableRecipe;
	TeamMemberCard: SlotTeamMemberCard;
	TooltipWithArrow: TooltipWithArrowProps;
}
