/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { TOKEN_DOCUMENT_FORMAT, TOKEN_KPI, TOKEN_SOFTWARE_BADGE, TOKEN_TYPOGRAPHY_ICON } from './enum';
export { KPI_TREND_ICON_NAME, LABEL_SIZE_CLASSES, RECORD_FONT_SIZE, TOKEN_FONT_FAMILY, TOKEN_LETTER_SPACING, TOKEN_LINE_HEIGHT } from './map';
export { DEFAULT_BADGE, DEFAULT_BADGE_LABEL, DEFAULT_CODE_BLOCK, LABEL_DEFAULTS, RECORD_TEXT_SIZE, THEME_TYPOGRAPHY } from './record';
export { BASE_LABEL_CLASSES, DEFAULT_LABEL_DISABLED, DEFAULT_LABEL_REQUIRED, LABEL_DISABLED_CLASSES, LABEL_ENABLED_CLASSES, REQUIRED_INDICATOR_CLASSES } from './value';