import { TOKEN_ICON_REGISTRY } from '$stylist/svg/const/record/icon-registry';

export const JOINT_TOOLBAR_ITEMS = [
	{ name: 'value',        svg: TOKEN_ICON_REGISTRY['value'] },
	{ name: 'enum',         svg: TOKEN_ICON_REGISTRY['enum'] },
	{ name: 'map',          svg: TOKEN_ICON_REGISTRY['map'] },
	{ name: 'record',       svg: TOKEN_ICON_REGISTRY['record'] },
	{ name: 'struct',       svg: TOKEN_ICON_REGISTRY['struct'] },
	{ name: 'config',       svg: TOKEN_ICON_REGISTRY['config'] },
	{ name: 'behavior',     svg: TOKEN_ICON_REGISTRY['behavior'] },
	{ name: 'slot',         svg: TOKEN_ICON_REGISTRY['slot'] },
	{ name: 'recipe',       svg: TOKEN_ICON_REGISTRY['recipe'] },
	{ name: 'contract',     svg: TOKEN_ICON_REGISTRY['contract'] },
	{ name: 'director',     svg: TOKEN_ICON_REGISTRY['director'] },
	{ name: 'builder',      svg: TOKEN_ICON_REGISTRY['builder'] },
	{ name: 'manager',      svg: TOKEN_ICON_REGISTRY['manager'] },
	{ name: 'object-manager', svg: TOKEN_ICON_REGISTRY['object-manager'] },
	{ name: 'style-manager', svg: TOKEN_ICON_REGISTRY['style-manager'] },
	{ name: 'script',       svg: TOKEN_ICON_REGISTRY['script'] },
	{ name: 'state',        svg: TOKEN_ICON_REGISTRY['state'] },
	{ name: 'atom',         svg: TOKEN_ICON_REGISTRY['atom'] },
	{ name: 'molecule',     svg: TOKEN_ICON_REGISTRY['molecule'] },
	{ name: 'organism',     svg: TOKEN_ICON_REGISTRY['organism'] },
	{ name: 'svg',          svg: TOKEN_ICON_REGISTRY['svg'] },
	{ name: 'json',         svg: TOKEN_ICON_REGISTRY['json'] },
	{ name: 'md',           svg: TOKEN_ICON_REGISTRY['md'] },
	{ name: 'yaml',         svg: TOKEN_ICON_REGISTRY['yaml'] },
	{ name: 'vert',         svg: TOKEN_ICON_REGISTRY['vert'] },
	{ name: 'frag',         svg: TOKEN_ICON_REGISTRY['frag'] }
] as const;
