import { TOKEN_ICON_REGISTRY } from '$stylist/svg/const/record/icon-registry';

export const JOINT_TOOLBAR_ITEMS = [
	{ name: 'json',           svg: TOKEN_ICON_REGISTRY['json'] },
	{ name: 'shader',         svg: TOKEN_ICON_REGISTRY['shader'] },
	{ name: 'svg',            svg: TOKEN_ICON_REGISTRY['svg'] },
	{ name: 'md',             svg: TOKEN_ICON_REGISTRY['md'] },
	{ name: 'yaml',           svg: TOKEN_ICON_REGISTRY['yaml'] },
	{ name: 'enum',           svg: TOKEN_ICON_REGISTRY['enum'] },
	{ name: 'value',          svg: TOKEN_ICON_REGISTRY['value'] },
	{ name: 'map',            svg: TOKEN_ICON_REGISTRY['map'] },
	{ name: 'record',         svg: TOKEN_ICON_REGISTRY['record'] },
	{ name: 'struct',         svg: TOKEN_ICON_REGISTRY['struct'] },
	{ name: 'preset',         svg: TOKEN_ICON_REGISTRY['preset'] },
	{ name: 'set',            svg: TOKEN_ICON_REGISTRY['set'] },
	{ name: 'array',          svg: TOKEN_ICON_REGISTRY['array'] },
	{ name: 'object',         svg: TOKEN_ICON_REGISTRY['object'] },
	{ name: 'alias',          svg: TOKEN_ICON_REGISTRY['alias'] },
	{ name: 'behavior',       svg: TOKEN_ICON_REGISTRY['behavior'] },
	{ name: 'slot',           svg: TOKEN_ICON_REGISTRY['slot'] },
	{ name: 'recipe',         svg: TOKEN_ICON_REGISTRY['recipe'] },
	{ name: 'contract',       svg: TOKEN_ICON_REGISTRY['contract'] },
	{ name: 'manager',        svg: TOKEN_ICON_REGISTRY['manager'] },
	{ name: 'script',         svg: TOKEN_ICON_REGISTRY['script'] },
	{ name: 'state',          svg: TOKEN_ICON_REGISTRY['state'] },
	{ name: 'hook',           svg: TOKEN_ICON_REGISTRY['hook'] },
	{ name: 'transform',      svg: TOKEN_ICON_REGISTRY['transform'] },
	{ name: 'test',           svg: TOKEN_ICON_REGISTRY['test'] },
	{ name: 'async',          svg: TOKEN_ICON_REGISTRY['async'] },
	{ name: 'merge',          svg: TOKEN_ICON_REGISTRY['merge'] },
	{ name: 'check',          svg: TOKEN_ICON_REGISTRY['check'] },
	{ name: 'count',          svg: TOKEN_ICON_REGISTRY['count'] },
	{ name: 'atom',           svg: TOKEN_ICON_REGISTRY['atom'] },
	{ name: 'molecule',       svg: TOKEN_ICON_REGISTRY['molecule'] },
	{ name: 'organism',       svg: TOKEN_ICON_REGISTRY['organism'] },
	{ name: 'page',           svg: TOKEN_ICON_REGISTRY['page'] },
	{ name: 'template',       svg: TOKEN_ICON_REGISTRY['template'] }
] as const;
