import type { CodeBlockContract } from '$stylist/development/interface/component/code-block/contract';
import type { CodeDiffContract } from '$stylist/development/interface/component/code-diff/contract';
import type { ComponentPreviewContract } from '$stylist/development/interface/component/component-preview/contract';
import type { DocumentationBlockContract } from '$stylist/development/interface/component/documentation-block/contract';
import type { PrivacySettingsContract } from '$stylist/development/interface/component/privacy-settings/contract';
import type { PlaygroundHeroContract } from '$stylist/development/interface/component/playground-hero/contract';
import type { PlaygroundShellHeaderContract } from '$stylist/development/interface/component/playground-shell-header/contract';
import type { PlaygroundComponentCatalogContract } from '$stylist/development/interface/component/playground-component-catalog/contract';
import type { PlaygroundComponentInfoCardContract } from '$stylist/development/interface/component/playground-component-info-card/contract';
import type { PlaygroundCodeViewerContract } from '$stylist/development/interface/component/playground-code-viewer/contract';
import type { PlaygroundDeviceFrameContract } from '$stylist/development/interface/component/playground-device-frame/contract';
import type { PlaygroundToastContract } from '$stylist/development/interface/component/playground-toast/contract';
import type { DebugConsoleContract } from '$stylist/development/interface/component/debug-console/contract';
import type { DesignTokensContract } from '$stylist/development/interface/component/design-tokens/contract';
import type { ComponentLibraryStatsContract } from '$stylist/development/interface/component/component-library-stats/contract';
import type { AtomicPrinciplesShowcaseContract } from '$stylist/development/interface/component/atomic-principles-showcase/contract';
import type { DevelopmentErrorBoundaryContract } from '$stylist/development/interface/component/development-error-boundary/contract';
import type { MockDataSelectorContract } from '$stylist/development/interface/component/mock-data-selector/contract';
import type { PlaygroundCanvasShellContract } from '$stylist/development/interface/component/playground-canvas-shell/contract';
import type { PlaygroundComponentTreeContract } from '$stylist/development/interface/component/playground-component-tree/contract';
import type { PlaygroundCtaButtonsContract } from '$stylist/development/interface/component/playground-cta-buttons/contract';
import type { PlaygroundAnimatedBackgroundContract } from '$stylist/development/interface/component/playground-animated-background/contract';
import type { PlaygroundMissionBannerContract } from '$stylist/development/interface/component/playground-mission-banner/contract';
import type { PlaygroundScreenshotSelectorContract } from '$stylist/development/interface/component/playground-screenshot-selector/contract';
import type { PlaygroundShortcutsPanelContract } from '$stylist/development/interface/component/playground-shortcuts-panel/contract';
import type { PlaygroundFeatureGridContract } from '$stylist/development/interface/component/playground-feature-grid/contract';
import type { PlaygroundLiveCodeSectionContract } from '$stylist/development/interface/component/playground-live-code-section/contract';
import type { PlaygroundMarkdownRendererContract } from '$stylist/development/interface/component/playground-markdown-renderer/contract';
import type { PlaygroundTreeNodeContract } from '$stylist/development/interface/component/playground-tree-node/contract';
import type { PlaygroundEnhancedExportPanelContract } from '$stylist/development/interface/component/playground-enhanced-export-panel/contract';
import type { PlaygroundErrorBoundaryContract } from '$stylist/development/interface/component/playground-error-boundary/contract';
import type { PlaygroundGenericCodeViewerContract } from '$stylist/development/interface/component/playground-generic-code-viewer/contract';
import type { PlaygroundDrawingOverlayContract } from '$stylist/development/interface/component/playground-drawing-overlay/contract';
import type { ResourceOptimizerContract } from '$stylist/development/interface/component/resource-optimizer/contract';
import type { StylistContract } from '$stylist/development/interface/component/stylist/contract';
import type { PlaygroundAiAssistantContract } from '$stylist/development/interface/component/playground-ai-assistant/contract';
import type { PlaygroundAiChatContract } from '$stylist/development/interface/component/playground-ai-chat/contract';
import type { PlaygroundAiPanelContract } from '$stylist/development/interface/component/playground-ai-panel/contract';

export interface MapDevelopmentContract {
	CodeBlock: CodeBlockContract;
	CodeDiff: CodeDiffContract;
	ComponentPreview: ComponentPreviewContract;
	DocumentationBlock: DocumentationBlockContract;
	PrivacySettings: PrivacySettingsContract;
	PlaygroundHero: PlaygroundHeroContract;
	PlaygroundShellHeader: PlaygroundShellHeaderContract;
	PlaygroundComponentCatalog: PlaygroundComponentCatalogContract;
	PlaygroundComponentInfoCard: PlaygroundComponentInfoCardContract;
	PlaygroundCodeViewer: PlaygroundCodeViewerContract;
	PlaygroundDeviceFrame: PlaygroundDeviceFrameContract;
	PlaygroundToast: PlaygroundToastContract;
	DebugConsole: DebugConsoleContract;
	DesignTokens: DesignTokensContract;
	ComponentLibraryStats: ComponentLibraryStatsContract;
	AtomicPrinciplesShowcase: AtomicPrinciplesShowcaseContract;
	DevelopmentErrorBoundary: DevelopmentErrorBoundaryContract;
	MockDataSelector: MockDataSelectorContract;
	PlaygroundCanvasShell: PlaygroundCanvasShellContract;
	PlaygroundComponentTree: PlaygroundComponentTreeContract;
	PlaygroundCtaButtons: PlaygroundCtaButtonsContract;
	PlaygroundAnimatedBackground: PlaygroundAnimatedBackgroundContract;
	PlaygroundMissionBanner: PlaygroundMissionBannerContract;
	PlaygroundScreenshotSelector: PlaygroundScreenshotSelectorContract;
	PlaygroundShortcutsPanel: PlaygroundShortcutsPanelContract;
	PlaygroundFeatureGrid: PlaygroundFeatureGridContract;
	PlaygroundLiveCodeSection: PlaygroundLiveCodeSectionContract;
	PlaygroundMarkdownRenderer: PlaygroundMarkdownRendererContract;
	PlaygroundTreeNode: PlaygroundTreeNodeContract;
	PlaygroundEnhancedExportPanel: PlaygroundEnhancedExportPanelContract;
	PlaygroundErrorBoundary: PlaygroundErrorBoundaryContract;
	PlaygroundGenericCodeViewer: PlaygroundGenericCodeViewerContract;
	PlaygroundDrawingOverlay: PlaygroundDrawingOverlayContract;
	ResourceOptimizer: ResourceOptimizerContract;
	Stylist: StylistContract;
	PlaygroundAiAssistant: PlaygroundAiAssistantContract;
	PlaygroundAiChat: PlaygroundAiChatContract;
	PlaygroundAiPanel: PlaygroundAiPanelContract;
}
