/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { PERIODIC_ELEMENTS } from './array';
export {
	ELEMENT_ABSORPTION_SPECTRAL_LINES,
	PERIODIC_ELEMENT_CATEGORY_ACCENT,
	PERIODIC_ELEMENT_DETAIL,
	PERIODIC_ELEMENT_LIGHT_INTERACTION
} from './record';
