import type { IAccordionProps } from '$stylist/interaction/interface/accordion';
import type { IAdvancedAccordionProps } from '$stylist/interaction/interface/advanced-accordion';
import type { AdvancedColorPickerProps } from '$stylist/interaction/interface/advanced-color-picker';
import type { IAdvancedPasswordInputProps } from '$stylist/interaction/interface/advanced-password-input';
import type { BurgerMenuProps } from '$stylist/interaction/interface/burger-menu';
import type { ButtonElementProps } from '$stylist/interaction/interface/button';
import type { ChatStatusIndicatorProps } from '$stylist/interaction/interface/chat-status-indicator';
import type { ClickProps } from '$stylist/interaction/interface/click';
import type { DialogProps, ModalProps } from '$stylist/interaction/interface/dialog-controls';
import type { DragAndDropProps } from '$stylist/interaction/interface/drag-and-drop';
import type { IDropdownMenuProps } from '$stylist/interaction/interface/dropdown-menu';
import type { IErrorBoundaryProps } from '$stylist/interaction/interface/error-boundary';
import type { ErrorMessageProps } from '$stylist/interaction/interface/error-message';
import type { FeatureToggleProps } from '$stylist/interaction/interface/feature-toggle';
import type { IIconPickerProps } from '$stylist/interaction/interface/icon-picker';
import type {
	LazyLoaderProps,
	LoadingBoundaryProps,
	ResponseViewerProps
} from '$stylist/interaction/interface/interaction-feedback';
import type { LocaleSwitcherProps } from '$stylist/interaction/interface/locale-switcher';
import type { MenuItemProps } from '$stylist/interaction/interface/menu-item';
import type { MultiSelectProps } from '$stylist/interaction/interface/multi-select';
import type { INumberInputProps } from '$stylist/interaction/interface/number-input';
import type { ILoadingOverlayProps } from '$stylist/interaction/interface/overlay';
import type { PaginationProps } from '$stylist/interaction/interface/pagination';
import type { IPhoneNumberInputProps } from '$stylist/interaction/interface/phone-number-input';
import type { IQuantitySelectorProps } from '$stylist/interaction/interface/quantity-selector';
import type { RangeInputProps } from '$stylist/interaction/interface/range-input';
import type { IRangeSliderProps } from '$stylist/interaction/interface/range-slider';
import type { IRatingProps } from '$stylist/interaction/interface/rating';
import type { IReactionPickerProps } from '$stylist/interaction/interface/reaction-picker';
import type { ISearchBarProps } from '$stylist/interaction/interface/search-bar';
import type { ISelectProps } from '$stylist/interaction/interface/selector';
import type { SortableTableHeaderProps } from '$stylist/interaction/interface/sortable-table-header';
import type { SwitchProps } from '$stylist/interaction/interface/switch';
import type { ISwitchWithLabelProps } from '$stylist/interaction/interface/switch-with-label';
import type { ITabGroupProps } from '$stylist/interaction/interface/tab-group';
import type { TabsProps } from '$stylist/interaction/interface/tabs';
import type { TagInputProps } from '$stylist/interaction/interface/tag-input';
import type { TooltipProps } from '$stylist/interaction/interface/tooltip';
import type { TransformationProps } from '$stylist/interaction/interface/transformation';
import type { TranslationEditorProps } from '$stylist/interaction/interface/translation-editor';
import type { ZoomControlsProps } from '$stylist/interaction/interface/zoom-controls';

export interface MapInteractionContract {
	Accordion: IAccordionProps;
	AdvancedAccordion: IAdvancedAccordionProps;
	AdvancedColorPicker: AdvancedColorPickerProps;
	AdvancedPasswordInput: IAdvancedPasswordInputProps;
	BurgerMenu: BurgerMenuProps;
	Button: ButtonElementProps;
	ChatStatusIndicator: ChatStatusIndicatorProps;
	Click: ClickProps;
	Dialog: DialogProps;
	Modal: ModalProps;
	DragAndDrop: DragAndDropProps;
	DropdownMenu: IDropdownMenuProps;
	ErrorBoundary: IErrorBoundaryProps;
	ErrorMessage: ErrorMessageProps;
	FeatureToggle: FeatureToggleProps;
	IconPicker: IIconPickerProps;
	LazyLoader: LazyLoaderProps;
	LoadingBoundary: LoadingBoundaryProps;
	ResponseViewer: ResponseViewerProps;
	LocaleSwitcher: LocaleSwitcherProps;
	MenuItem: MenuItemProps;
	MultiSelect: MultiSelectProps;
	NumberInput: INumberInputProps;
	LoadingOverlay: ILoadingOverlayProps;
	Pagination: PaginationProps;
	PhoneNumberInput: IPhoneNumberInputProps;
	QuantitySelector: IQuantitySelectorProps;
	RangeInput: RangeInputProps;
	RangeSlider: IRangeSliderProps;
	Rating: IRatingProps;
	ReactionPicker: IReactionPickerProps;
	SearchBar: ISearchBarProps;
	Selector: ISelectProps;
	SortableTableHeader: SortableTableHeaderProps;
	Switch: SwitchProps;
	SwitchWithLabel: ISwitchWithLabelProps;
	TabGroup: ITabGroupProps;
	Tabs: TabsProps;
	TagInput: TagInputProps;
	Tooltip: TooltipProps;
	Transformation: TransformationProps;
	TranslationEditor: TranslationEditorProps;
	ZoomControls: ZoomControlsProps;
}
