/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { BLOCKQUOTE_CLASSES, DEFAULT_WITH_BACKGROUND, DEFAULT_WITH_BORDER, FOOTER_PREFIX, getBlockquoteClasses } from './block';
export { BADGE_DEFAULT_SIZE, BADGE_DEFAULT_VARIANT, DEFAULT_CODE_BLOCK_SIZE, DEFAULT_CODE_BLOCK_VARIANT, DEFAULT_LABEL_DISABLED, DEFAULT_LABEL_REQUIRED, DEFAULT_LABEL_SIZE, DEFAULT_LANGUAGE, DEFAULT_SHOW_LINE_NUMBERS, DEFAULT_START_LINE_NUMBER, getBadgeClasses, getBadgeGroupContainerClasses, getBadgeGroupOverflowClasses, getCodeBlockClasses, getLabelClasses, getRequiredIndicatorClasses } from './elements';
export { DEFAULT_COUNTER_COUNT, DEFAULT_COUNTER_MAX, DEFAULT_COUNTER_SIZE, DEFAULT_COUNTER_VARIANT, DEFAULT_COUNT_BADGE_COUNT, DEFAULT_COUNT_BADGE_MAX, DEFAULT_COUNT_BADGE_SHOW_ZERO, DEFAULT_DOT_COLOR, DEFAULT_DOT_SIZE, DEFAULT_MARKER_COLOR, DEFAULT_MARKER_SIZE, DEFAULT_MARKER_TYPE, DEFAULT_MARKER_VALUE, DEFAULT_STATUS_INDICATOR_STATUS, getBulletClasses, getCountBadgeClasses, getCounterClasses, getDotClasses, getMarkerClasses, getMessageStatusContainerClasses, getMessageStatusIconClasses, getStatusIndicatorContainerClasses, getStatusIndicatorDotClasses, getStatusIndicatorLabel, getStatusIndicatorWithLabelContainerClasses, getStatusIndicatorWithLabelIndicatorClasses, getStatusIndicatorWithLabelLabelClasses, getStatusIndicatorWithLabelSizeClasses } from './indicators';
export { DEFAULT_ABBR_TITLE, DEFAULT_INLINE_CODE_VARIANT, DEFAULT_LINK_DISABLED, DEFAULT_LINK_SIZE, DEFAULT_LINK_UNDERLINE, DEFAULT_LINK_VARIANT, DEFAULT_SEPARATOR_DECORATIVE, DEFAULT_SEPARATOR_ORIENTATION, DEFAULT_SYNTAX_HIGHLIGHTED_CODE_SIZE, DEFAULT_SYNTAX_HIGHLIGHTED_CODE_VARIANT, getAbbrClasses, getDefinitionDescriptionClasses, getDefinitionTermClasses, getEmClasses, getHighlightClasses, getInlineCodeClasses, getKbdClasses, getLinkClasses, getSeparatorClasses, getSyntaxHighlightedCodeClasses, getSyntaxHighlightedCodeContainerClasses } from './inline';
export type { BadgeSize, BadgeVariant, CodeBlockSize, CodeBlockVariant, LabelSize } from './elements';
export type { CounterSize, CounterVariant, DotColor, DotSize, IndicatorStatus, ListItemColor, ListItemSize, MarkerType, MessageStatusSize, MessageStatusType, StatusIndicatorLabelStatus } from './indicators';
export type { InlineCodeVariant, LinkSize, LinkVariant, SeparatorOrientation, SyntaxHighlightedCodeSize, SyntaxHighlightedCodeVariant } from './inline';
export type { BlockquoteProps } from './block';
export type { BadgeGroupItem, BadgeGroupProps, BadgeProps, CodeBlockProps, LabelProps } from './elements';
export type { CountBadgeProps, CounterProps, DotProps, ListItemMarkerProps, MessageStatusProps, StatusIndicatorProps, StatusIndicatorWithLabelProps } from './indicators';
export type { AbbrProps, DefinitionDescriptionProps, DefinitionTermProps, EmProps, HighlightProps, InlineCodeProps, KbdProps, LinkProps, SeparatorProps, SyntaxHighlightedCodeProps } from './inline';
export type { CaptionProps, HeadingProps, ParagraphProps, SmallProps, StrikethroughProps, StrongProps, SubscriptProps, SuperscriptProps, TextProps } from './text';
export { getCaptionClasses } from './text';