import type { HTMLAttributes } from 'svelte/elements';
import type { OrderItem } from '$stylist/commerce/type/struct/order-item';
import type { ShippingAddress } from '$stylist/commerce/type/struct/shipping-address';
import type { PaymentInfo } from '$stylist/commerce/type/struct/payment-info';

export type OrderConfirmationProps = Omit<HTMLAttributes<HTMLDivElement>, 'class'> & {
	orderId: string;
	orderDate: Date;
	items: OrderItem[];
	total: number;
	shippingAddress: ShippingAddress;
	paymentInfo: PaymentInfo;
	estimatedDelivery?: Date;
	trackingNumber?: string;
	orderStatus?: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled';
	shippingCost?: number;
	taxAmount?: number;
	class?: string;
	headerClass?: string;
	summaryClass?: string;
	itemClass?: string;
	addressClass?: string;
	actionsClass?: string;
	showDownloadInvoice?: boolean;
	showShareOrder?: boolean;
	onDownloadInvoice?: () => void;
	onShareOrder?: () => void;
	onContinueShopping?: () => void;
	onTrackOrder?: () => void;
	currency?: string;
	locale?: string;
};
