/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { VEHICLE_TYPES } from './array';
export {
	SAMPLE_ADMIN_ADDONS,
	SAMPLE_ADMIN_PICKUP_POINTS,
	SAMPLE_ADMIN_PRODUCTS,
	SAMPLE_ADMIN_ROUTE_STOPS,
	SAMPLE_ADMIN_TRANSFER_RATES
} from './preset';
