import { ACCESSIBILITY_CLASSES, BASE_CLASSES, DEFAULT_FLAGS, STATE_CLASSES } from '../tokens/classes';
import { COMPONENT_SIZE_SCALE, COMPACT_SIZE_SCALE, ICON_SIZES, SIZE_CLASSES } from '../tokens/sizes';
import { INTERACTIVE_VARIANTS, VARIANT_CLASSES } from '../tokens/interaction';

export const INTERACTIVE_BASE_CLASS = BASE_CLASSES.interactive;

export const INTERACTION_TOKENS = {
  INTERACTIVE_VARIANTS,
  COMPONENT_SIZE_SCALE,
  COMPACT_SIZE_SCALE,
  DEFAULT_FLAGS,
  STATE_CLASSES,
  INTERACTIVE_BASE_CLASS,
  ACCESSIBILITY_CLASSES,
  VARIANT_CLASSES,
  SIZE_CLASSES,
  ICON_SIZES
} as const;
