import type { IAccordionProps } from '$stylist/control/interface/component/accordion/other';
import type { IAdvancedAccordionProps } from '$stylist/control/interface/component/advanced-accordion';
import type { ThemeAdvancedColorPickerRecipe } from '$stylist/color/interface/recipe/advanced-color-picker';
import type { IAdvancedPasswordInputProps } from '$stylist/input/interface/component/advanced-password-input/other';
import type { BurgerMenuProps } from '$stylist/control/interface/component/burger-menu/other';
import type { ButtonElementProps } from '$stylist/control/interface/component/button/other';
import type { ChatStatusIndicatorProps } from '$stylist/communication/interface/component/chat-status-indicator/other';
import type { ClickProps } from '$stylist/control/interface/component/click/other';
import type { DialogProps, ModalProps } from '$stylist/navigation/interface/component/dialog-controls/other';
import type { DragAndDropProps } from '$stylist/control/interface/component/drag-and-drop/other';
import type { IDropdownMenuProps } from '$stylist/control/interface/component/dropdown-menu/other';
import type { IErrorBoundaryProps } from '$stylist/notification/interface/component/error-boundary/other';
import type { ErrorMessageProps } from '$stylist/notification/interface/component/error-message/other';
import type { FeatureToggleProps } from '$stylist/management/interface/component/feature-toggle/other';
import type { ThemeIconPickerRecipe } from '$stylist/media/interface/recipe/icon-picker';
import type {
	LazyLoaderProps,
	LoadingBoundaryProps,
	ResponseViewerProps
} from '$stylist/notification/interface/component/interaction-feedback/other';
import type { LocaleSwitcherProps } from '$stylist/localization/interface/component/locale-switcher/other';
import type { MenuItemProps } from '$stylist/control/interface/component/menu-item/other';
import type { MultiSelectProps } from '$stylist/control/interface/component/multi-select/other';
import type { INumberInputProps } from '$stylist/input/interface/component/number-input/other';
import type { ILoadingOverlayProps } from '$stylist/notification/interface/component/overlay/other';
import type { PaginationProps } from '$stylist/navigation/interface/component/pagination/other';
import type { IPhoneNumberInputProps } from '$stylist/input/interface/component/phone-number-input/other';
import type { IQuantitySelectorProps } from '$stylist/control/interface/component/quantity-selector/other';
import type { RangeInputProps } from '$stylist/input/interface/component/range-input/other';
import type { IRangeSliderProps } from '$stylist/input/interface/component/range-slider/other';
import type { IRatingProps } from '$stylist/social/interface/component/rating/other';
import type { IReactionPickerProps } from '$stylist/input/interface/component/reaction-picker/other';
import type { ISearchBarProps } from '$stylist/control/interface/component/search-bar/other';
import type { ISelectProps } from '$stylist/control/interface/component/selector/other';
import type { SortableTableHeaderProps } from '$stylist/control/interface/component/sortable-table-header/other';
import type { SwitchProps } from '$stylist/control/interface/component/switch/other';
import type { ISwitchWithLabelProps } from '$stylist/control/interface/component/switch-with-label/other';
import type { ITabGroupProps } from '$stylist/control/interface/component/tab-group/other';
import type { TabsProps } from '$stylist/control/interface/component/tabs/other';
import type { TagInputProps } from '$stylist/input/interface/component/tag-input/other';
import type { TooltipProps } from '$stylist/control/interface/component/tooltip/other';
import type { TransformationProps } from '$stylist/control/interface/component/transformation/other';
import type { TranslationEditorProps } from '$stylist/localization/interface/component/translation-editor/other';
import type { ZoomControlsProps } from '$stylist/control/interface/component/zoom-controls/other';

export interface MapInteractionContract {
	Accordion: IAccordionProps;
	AdvancedAccordion: IAdvancedAccordionProps;
	AdvancedColorPicker: ThemeAdvancedColorPickerRecipe;
	AdvancedPasswordInput: IAdvancedPasswordInputProps;
	BurgerMenu: BurgerMenuProps;
	Button: ButtonElementProps;
	ChatStatusIndicator: ChatStatusIndicatorProps;
	Click: ClickProps;
	Dialog: DialogProps;
	Modal: ModalProps;
	DragAndDrop: DragAndDropProps;
	DropdownMenu: IDropdownMenuProps;
	ErrorBoundary: IErrorBoundaryProps;
	ErrorMessage: ErrorMessageProps;
	FeatureToggle: FeatureToggleProps;
	IconPicker: ThemeIconPickerRecipe;
	LazyLoader: LazyLoaderProps;
	LoadingBoundary: LoadingBoundaryProps;
	ResponseViewer: ResponseViewerProps;
	LocaleSwitcher: LocaleSwitcherProps;
	MenuItem: MenuItemProps;
	MultiSelect: MultiSelectProps;
	NumberInput: INumberInputProps;
	LoadingOverlay: ILoadingOverlayProps;
	Pagination: PaginationProps;
	PhoneNumberInput: IPhoneNumberInputProps;
	QuantitySelector: IQuantitySelectorProps;
	RangeInput: RangeInputProps;
	RangeSlider: IRangeSliderProps;
	Rating: IRatingProps;
	ReactionPicker: IReactionPickerProps;
	SearchBar: ISearchBarProps;
	Selector: ISelectProps;
	SortableTableHeader: SortableTableHeaderProps;
	Switch: SwitchProps;
	SwitchWithLabel: ISwitchWithLabelProps;
	TabGroup: ITabGroupProps;
	Tabs: TabsProps;
	TagInput: TagInputProps;
	Tooltip: TooltipProps;
	Transformation: TransformationProps;
	TranslationEditor: TranslationEditorProps;
	ZoomControls: ZoomControlsProps;
}
