import type { StructIntersectAll } from '$stylist/architecture/type/struct/intersect-all';
import type { TokenSize } from '$stylist/layout/type/enum/size';
import type { ThemeAttributes } from '$stylist/theme/type/struct/theme-attributes';
import type { LiteGraphNodeProperty } from '$stylist/science/type/struct/litegraph-node-property';
import type { LiteGraphPort } from '$stylist/science/type/struct/litegraph-port';
import type { LitegraphNodePresentation } from '$stylist/science/type/struct/litegraph-node-presentation';

export interface LitegraphNodeRecipe extends StructIntersectAll<[ThemeAttributes<HTMLDivElement>]> {
	id?: string;
	title?: string;
	x: number;
	y: number;
	type?: 'default' | 'custom' | 'source' | 'processor' | 'output' | 'gateway';
	mode?: string;
	status?: string;
	size?: TokenSize;
	selected?: boolean;
	draggable?: boolean;
	selectable?: boolean;
	resizable?: boolean;
	deletable?: boolean;
	duplicable?: boolean;
	width?: number;
	minWidth?: number;
	height?: number | 'auto';
	color?: string;
	headerColor?: string;
	hideHeader?: boolean;
	hidePorts?: boolean;
	hideProperties?: boolean;
	showActions?: boolean;
	worldDepth?: number;
	cameraDepth?: number;
	presentation?: LitegraphNodePresentation;
	properties?: LiteGraphNodeProperty[];
	inputs?: LiteGraphPort[];
	outputs?: LiteGraphPort[];
	headerContent?: string;
	bodyContent?: string;
}
