/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export {
	LIST_ITEM_MARKER_TYPE,
	STATUS_STATE,
	TOKEN_SOFTWARE_BADGE
} from './array';
export {
	DEFAULT_BADGE,
	DEFAULT_BADGE_LABEL
} from './record';
