/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export type { ABTest, ABTestVariant } from './abtest-configurator';
export type { AuthRole } from './auth-guard';
export type { BaseTagSize, BaseTagVariant } from './badge';
export type { ColorScheme } from './bar-chart';
export type { BillingItemStatus, BillingSummaryStatus } from './billing-summary';
export type { PageEllipsisProps } from './breadcrumbs';
export type { ButtonElementProps } from './button';
export type { CalendarDay, CalendarEvent, CalendarViewMode } from './calendar';
export type { CanvasImageEditorProps, CropArea, ImageFilter } from './canvas-image-editor';
export type { ChartDataPoint } from './chart';
export type { ChatMessageStatus, ChatMessageVariant } from './chat';
export type { CommentItem, CommentUser } from './comment-system';
export type { CommentThreadItem, CommentThreadUser } from './comment-thread';
export type { BlockquoteAttributesBase, ButtonAttributesBase, ButtonAttributesWithChildren, CharacterCountVariant, InputAddonVariant, InputHtmlType, InteractionState, LoadingState, PinInputVariant, ValidationState, VisibilityState } from './common';
export type { DownloadCardVariant } from './download-card';
export type { DropdownPosition } from './dropdown-menu';
export type { NotificationBadgePosition, NotificationBadgeVariant, ProgressBarSize, ProgressBarVariant, SpinnerSize, StepIconSize, StepIconStatus } from './feedback';
export type { GeoJSONViewerRestProps, GeoJsonFeature, GeoJsonFeatureCollection, GeoJsonGeometry, GeoJsonLayer, MapView } from './geo-jsonviewer';
export type { GradientVariant } from './gradient-background';
export type { GraphNodeSize, GraphNodeType } from './graph';
export type { THeatmapColorScheme } from './heatmap';
export type { HeroBackgroundVariant, HeroHeight } from './hero';
export type { THighContrastTheme } from './high-contrast-toggle';
export type { IIconPickerRestProps, TColumns } from './icon-picker';
export type { InputAddonPosition } from './input';
export type { SelectSize, SelectVariant, ToolbarVariant } from './interaction';
export type { NotificationItem } from './interaction-feedback';
export type { AutoCompleteOption, DateRangeValue, DateTimeRangeValue, ProductForQuote, QuoteRequestValue, TranslatableText, TranslationLocale, TranslationStatus } from './interaction-input';
export type { KPIIndicatorSize, KPIStatus, KPITrend } from './kpiindicator';
export type { ContainerMaxWidth, GridItem, GridItemContent, SpacerAxis } from './layout';
export type { LineChartData, LineChartPoint, LineChartSize, LineChartVariant } from './line-chart';
export type { LinkCardVariant } from './link-card';
export type { LocaleSwitcherLocale, LocaleSwitcherTimezoneOption } from './locale-switcher';
export type { ContactInfo, Coordinates, MarkerCategory, MarkerType, PinStyle } from './map-marker';
export type { MessageAlign, MessageBubbleVariant } from './message-bubble';
export type { MetricCardVariant } from './metric-card';
export type { Model, ModelSelectorProps } from './model-selector';
export type { CodeLanguage, EdgeStyle, PropType, WishlistButtonSize, WishlistButtonVariant, WishlistTooltipPosition } from './molecules-migration';
export type { MultiSelectOption } from './multi-select';
export type { NotificationPosition, NotificationType } from './notification';
export type { INotificationPreference, NotificationChannel } from './notification-settings';
export type { IOrderConfirmationEvents, IOrderConfirmationProps, OrderConfirmationPaymentInfo, OrderItem, OrderStatus, PaymentStatus, ShippingAddress } from './order-confirmation';
export type { LoadingOverlaySpinnerSize } from './overlay';
export type { PageBuilderElementAttributes, PageBuilderElementType } from './page-builder';
export type { PaginationProps, PaginationSize, PaginationVariant } from './pagination';
export type { PaymentMethod, PaymentMethodType, PaymentSummaryDiscount, PaymentSummaryItem, PaymentSummaryTax } from './payment-controls';
export type { Prediction, PredictionResultStatus } from './prediction-result';
export type { PromptTemplate, PromptVariable } from './prompt-builder';
export type { QuantitySelectorSize, QuantitySelectorVariant } from './quantity-selector';
export type { RatingSize } from './rating';
export type { ScatterPlotDataPoint } from './scatter-plot';
export type { EventPriority, ScheduleEvent } from './schedule-calendar';
export type { SearchResultItem } from './search-results';
export type { SentimentResult } from './sentiment-analysis';
export type { NavItem, SidebarPosition, SidebarProps, SidebarVariant } from './sidebar';
export type { StatCardVariant, StatTrend } from './stat-card';
export type { LabelPosition } from './switch-with-label';
export type { TabGroupVariant } from './tab-group';
export type { TableCellAlign, TableSectionProps } from './table';
export type { ColumnConfig, SortableListItem } from './table-controls';
export type { TableRecord } from './table-extended';
export type { TabContainerProps, TabIndicatorColor } from './tabs';
export type { TeamMemberCardVariant } from './team-member-card';
export type { ToastType } from './toast';
export type { ToggleGroupType, ToggleSize } from './toggles';
export type { TreeNode } from './tree-controls';
export type { UserStatusScenario, UserStatusStoryUser } from './user-status';
export type { IABTestConfiguratorProps } from './abtest-configurator';
export type { AccordionBaseProps, AccordionHeaderDoubleProps, AccordionHeaderProps, AccordionItemProps, AccordionPanelProps, ComplexAccordionProps, IAccordionProps } from './accordion';
export type { AccountSettingsFormProps, UserProfileCardProps } from './account-forms';
export type { IAdvancedAccordionItem, IAdvancedAccordionProps } from './advanced-accordion';
export type { IAdvancedPasswordInputProps } from './advanced-password-input';
export type { IAiResultCardProps } from './ai-result-card';
export type { IAlertAction, IAlertCardProps } from './alert-card';
export type { AnimatedNumberProps, NumberFlowProps } from './animation';
export type { AuthGuardProps } from './auth-guard';
export type { BadgeGroupItem, BadgeGroupProps, BadgeProps, BaseTagProps, ChipProps, CodeBlockProps, NpmBadgeProps, TagProps } from './badge';
export type { IBarChartProps, IBarPosition, IChartDataPoint } from './bar-chart';
export type { IBillingItem, IBillingSummaryProps } from './billing-summary';
export type { BlockquoteProps } from './blockquote';
export type { IBreadcrumbItem, IBreadcrumbLinkProps, IBreadcrumbProps, IBreadcrumbsCrumb, IBreadcrumbsProps } from './breadcrumbs';
export type { ButtonControlProps, CopyButtonProps, IconButtonProps, PageButtonProps } from './button';
export type { ICategoryCardProps } from './category-card';
export type { ColorSwatchProps, PieChartProps } from './chart';
export type { Chat, ChatMessageProps, Message, MessageAttachment, MessageInputProps, MessageReaction, MessageThreadMessage, MessageThreadProps, User } from './chat';
export type { CommentSystemProps } from './comment-system';
export type { CommentThreadProps } from './comment-thread';
export type { ChildrenProp, ClassProp, ComponentStateProps, ContentProp, HtmlAttributesBase, HtmlAttributesWithChildren, HtmlAttributesWithContent, HtmlStateAttr, HtmlVariantSizeAttr, IClickable, IDisableable, ILoadable, ISize, IStyleable, IVariant, InputAttributesBase, InputFieldBaseProps, InputFieldRequiredProps, InputLabelProps, InputValidationProps, InputValueProps, Props, StateProps, StateStyleProps, TextInputBaseProps, TypographyTextProps } from './common';
export type { IComparisonCardProps, IComparisonData, IComparisonItem } from './comparison-card';
export type { CountryFlagProps } from './countryflag';
export type { DialogProps, ModalProps } from './dialog-controls';
export type { IDownloadCardProps, IFileMetadata } from './download-card';
export type { IDropdownMenuProps, IDropdownMenuStyleClasses } from './dropdown-menu';
export type { IErrorBoundaryDetails, IErrorBoundaryProps } from './error-boundary';
export type { IEventCalendarProps } from './event-calendar';
export type { IExpandableCardProps } from './expandable-card';
export type { FeatureToggleProps } from './feature-toggle';
export type { IAccountProgressTrackerProps, IAlertProps, IBaseFeedbackProps, IErrorMessageProps, ILoaderProps, INotificationBadgeProps, IProgressBarProps, IProgressCircleProps, ISimpleTooltipProps, ISkeletonProps, ISpinnerProps, IStepConnectorProps, IStepIconProps, ITableSkeletonProps } from './feedback';
export type { IGeoJSONViewerProps } from './geo-jsonviewer';
export type { IGradientBackgroundProps } from './gradient-background';
export type { GraphEdgeProps, GraphNodeProps } from './graph';
export type { IExtendedHeatmapCell, IHeatmapCell, IHeatmapProps } from './heatmap';
export type { IHeroCTA, IHeroProps, IHeroStat } from './hero';
export type { IHighContrastState, IHighContrastToggleProps } from './high-contrast-toggle';
export type { IIconItem, IIconPickerProps } from './icon-picker';
export type { IconChevronProps, IconCircleProps, IconWrapperProps } from './icons';
export type { AnnouncementBannerProps, FaviconProps, ImageWithCaptionProps, MediaContentProps, MediaHtmlChildrenProps, MediaHtmlProps, MediaIconBaseProps } from './image';
export type { IImageGalleryProps, IImageItem } from './image-gallery';
export type { CountBadgeProps, CounterProps, DotProps, ListItemMarkerProps, MessageStatusProps, StatusIndicatorProps, StatusIndicatorWithLabelProps } from './indicators';
export type { IAdvancedInputProps, ICharacterCountProps, IFormErrorMessageProps, IFormHelperTextProps, IInputAddonProps, IInputFieldProps, IInputGroupProps, IInputProps, IPinInputDigitProps, ITextareaProps, InputHelperChildrenProps, InputHelperProps, InputProps } from './input';
export type { ControlProps, InputControlProps, PictureToolbarProps, PictureToolbarTool, ProductSortOption, ProductSortProps, SelectControlProps, SelectOption, SelectProps, SliderProps, SliderTickProps, SortProps, TextAreaControlProps, ToolbarFieldProps, ToolbarGroupProps, ToolbarInteractiveProps, ToolbarProps, ToolbarSeparatorProps } from './interaction';
export type { LazyLoaderProps, LoadingBoundaryProps, NotificationCenterProps, NotificationListProps, NotificationPreferencesProps, ResponseViewerProps, ScheduledNotificationProps, SimpleModalProps } from './interaction-feedback';
export type { AddressFormProps, AppearanceSettingsProps, DocumentPreviewProps, FormWithValidationProps, LoginFormProps, ScreenReaderProps, SearchFormProps, SecureFormProps, SecuritySettingsProps, SessionManagerProps } from './interaction-forms';
export type { AdvancedColorPickerProps, AutoCompleteProps, DateRangePickerProps, DateTimeRangePickerProps, QuoteRequestProps, RangeInputProps, TagInputProps, TranslationEditorProps } from './interaction-input';
export type { IKPIIndicatorProps } from './kpiindicator';
export type { LabelProps } from './label';
export type { AspectRatioProps, ContainerProps, DividerProps, GridLayoutProps, HorizontalLayoutProps, SpacerProps } from './layout';
export type { ILineChartProps } from './line-chart';
export type { AbbrProps, InlineBaseProps, InlineCodeProps, LinkProps, TextProps } from './link';
export type { ILinkCardProps } from './link-card';
export type { LocaleSwitcherProps } from './locale-switcher';
export type { IMapMarkerProps } from './map-marker';
export type { IMessageBubbleProps } from './message-bubble';
export type { IMessageComposerProps } from './message-composer';
export type { IMessageMetaProps, IMessageMetaStyleClasses } from './message-meta';
export type { IMetricCardProps } from './metric-card';
export type { CodeEditorProps, GraphvizDirectedEdgeProps, ProductSearchProps, PropDefinition, PropsEditorProps, WishlistButtonProps } from './molecules-migration';
export type { MultiSelectProps } from './multi-select';
export type { INotificationProps } from './notification';
export type { INotificationSettingsPreference, INotificationSettingsProps } from './notification-settings';
export type { INumberInputProps } from './number-input';
export type { ILoadingOverlayProps } from './overlay';
export type { PageBuilderButtonAttributes, PageBuilderElement, PageBuilderHeadingAttributes, PageBuilderImageAttributes, PageBuilderProps, PageBuilderTextAttributes, PageBuilderToolbarItem } from './page-builder';
export type { IPageHeaderProps } from './page-header';
export type { PaymentInfoProps, PaymentMethodSelectorProps, PaymentSelectorProps, PaymentSummaryProps } from './payment-controls';
export type { IPhoneNumberInputProps } from './phone-number-input';
export type { PredictionResultProps } from './prediction-result';
export type { IProcessStepProps } from './process-step';
export type { IProductSortingProps, IProductSortingStyleClasses } from './product-sorting';
export type { PromptBuilderProps } from './prompt-builder';
export type { IQuantitySelectorProps } from './quantity-selector';
export type { IRangeSliderProps } from './range-slider';
export type { IRatingProps } from './rating';
export type { IReactionPickerProps, IReactionPickerStyleClasses } from './reaction-picker';
export type { ScatterPlotProps } from './scatter-plot';
export type { DaySchedule, IScheduleCalendarProps, ScheduleTimeSlot } from './schedule-calendar';
export type { ISearchBarEvents, ISearchBarProps } from './search-bar';
export type { SearchResultsProps } from './search-results';
export type { ISelectOption, ISelectProps, ISelectStyleClasses } from './selector';
export type { SentimentAnalysisProps } from './sentiment-analysis';
export type { SeparatorProps, SyntaxHighlightedCodeProps } from './separator';
export type { StackProps } from './stack';
export type { IStatCardProps } from './stat-card';
export type { ISwitchWithLabelProps } from './switch-with-label';
export type { ITab, ITabGroupProps, ITabStyleClasses } from './tab-group';
export type { TableAttributesBase, TableCellProps, TableElementAttributesBase, TableProps, TableRowProps } from './table';
export type { ColumnManagerProps, DataTableAdvancedProps, DataTableProps, SortableListProps } from './table-controls';
export type { TableWithFiltersProps, TableWithGroupingProps, TableWithStripesProps } from './table-extended';
export type { TabIndicatorProps, TabPanelProps, TabProps, TabsProps } from './tabs';
export type { IAchievement, ITeamMemberCardProps } from './team-member-card';
export type { ITimeSlot, ITimeSlotProps } from './time-slot';
export type { IToastProps, IToastStyleClasses } from './toast';
export type { ActionSegmentedControlProps, AdvancedToggleProps, CheckboxProps, DarkModeToggleProps, RadioButtonGroupProps, RadioProps, SwitchProps, ToggleBaseProps, ToggleGroupItemProps, ToggleGroupRootProps, ToggleInputProps, ToggleProps } from './toggles';
export type { AdvancedVirtualTreeProps, FlatTreeProps, FolderTreeProps, VirtualTreeProps } from './tree-controls';
export type { ITreeNodeItemProps, ITreeNodeItemStyleClasses, TreeNodeItemNode } from './tree-node-item';