export const TOKEN_FILE_ICON = [
	'archive',
	'attachment-preview',
	'cards',
	'controls',
	'data-exporter',
	'download',
	'download-card',
	'drag-drop-file-upload',
	'export',
	'file',
	'file-browser',
	'file-input',
	'file-list-item',
	'file-upload',
	'forms',
	'import',
	'input',
	'preview',
	'upload',
	'upload-progress'
] as const;
