/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export { ALIGNMENTS, ALL_VARIANTS, APPEARANCE_STYLES, AVATAR_SHAPES, BADGE_VARIANTS, BUTTON_SHAPES, CARD_SHAPES, CODE_BLOCK_SIZE_SCALE, CODE_BLOCK_VARIANTS, COLOR_VARIANTS, COMPACT_SIZE_SCALE, COMPONENT_SIZE_SCALE, EXTENDED_SIZE_SCALE, FLOW_VARIANTS, GEOMETRIC_SHAPES, ICON_WRAPPER_SHAPES, INPUT_VARIANTS, JUSTIFICATIONS, LABEL_SIZE_SCALE, MESSAGE_THREAD_VARIANTS, NEUTRAL_VARIANTS, ORIENTATIONS, POSITIONS, SEMANTIC_VARIANTS, SIZE_SCALES, SKELETON_VARIANTS, SPACER_SIZE_SCALE, STACK_ALIGNMENTS, STATE_VARIANTS, TABLE_CELL_VARIANTS, TEXT_ALIGNMENTS, VARIANT_TO_PALETTE, WRAPPER_SHAPES, aspectRatio, aspects, backdropBlur, blur, blurTokens, borderRadius, borderStyle, borderWidth, borders, breakpointRanges, breakpoints, containerMaxWidth, containerPadding, containers, gridColumns, gridGaps, grids, opacity, semanticOpacity, shadow, spacing } from './architecture';
export { BADGE_LABELS, DEFAULT_FLAGS, GRAPH_EDGE_DEFAULTS, GRAPH_EDGE_TYPES, amber, blue, colorPalettes, directionalGradients, fontFamily, fontSize, fontWeight, gradients, green, lineHeight, neutral, radialGradients, red, slate, teal, typography } from './information';
export { ACTIVITY_STATUSES, CONTROL_TYPES, LOADING_STATUSES, MARKER_TYPES, MESSAGE_STATUSES, NOTIFICATION_TYPES, PRESENCE_STATUSES, PROGRESS_TYPES, SEVERITY_LEVELS, animationDelay, animationTiming, animations, transition, transitionDuration, transitionEasing, zIndex } from './interaction';
export type { Alignment, AllVariants, AppearanceStyle, AspectRatio, AvatarShape, BackdropBlurKey, BadgeVariant, BlurKey, BorderRadiusKey, BorderStyle, BorderWidthKey, BreakpointKey, BreakpointRangeKey, ButtonShape, CardShape, CodeBlockSize, CodeBlockVariant, ColorVariant, CommonSize, CompactSize, ComponentSize, ContainerMaxWidthKey, ContainerPaddingKey, CountryFlagSize, DefaultVariants, ExtendedSize, FlowVariant, GeometricShape, GridColumnsKey, GridGapKey, IconWrapperShape, InputVariant, Justification, LabelSize, MessageThreadVariant, NeutralVariant, OpacityKey, Orientation, Placement, Position, SemanticOpacityKey, SemanticVariant, ShadowKey, SkeletonVariant, SpacerSize, SpacingKey, StackAlign, StateVariant, TableCellVariant, TextAlign, VariantExtendedSize, VariantPaletteName, VariantWithAppearance, WrapperShape } from './architecture';
export type { BadgeType, ColorPaletteName, DirectionalGradientKey, FontFamilyKey, FontSizeKey, FontWeightKey, GradientKey, GraphEdgeType, LineHeightKey, RadialGradientKey } from './information';
export type { ActivityStatus, AnimationDelayKey, AnimationTiming, ControlType, CounterVariant, IndicatorStatus, LoadingStatus, MarkerType, MessageStatusType, NotificationType, PresenceStatus, ProgressType, SeverityLevel, StatusIndicatorLabelStatus, TransitionDurationKey, TransitionEasingKey, TransitionKey, ZIndexKey } from './interaction';
export type { Position2D } from './architecture';
export type { ColorScale } from './information';
export type { ControlConfig } from './interaction';