import type { CommonSize } from './variants';
import {
	BADGE_DEFAULT_SIZE,
	BADGE_DEFAULT_VARIANT,
	BADGE_GROUP_CONTAINER_CLASSES,
	BADGE_GROUP_OVERFLOW_CLASSES,
	BADGE_SIZE_CLASSES,
	BADGE_VARIANT_CLASSES,
	BASE_BADGE_CLASSES,
	BASE_CODE_BLOCK_CLASSES,
	BASE_LABEL_CLASSES,
	CODE_BLOCK_SIZE_CLASSES,
	CODE_BLOCK_VARIANT_CLASSES,
	DEFAULT_CODE_BLOCK_SIZE,
	DEFAULT_CODE_BLOCK_VARIANT,
	DEFAULT_LABEL_DISABLED,
	DEFAULT_LABEL_REQUIRED,
	DEFAULT_LABEL_SIZE,
	DEFAULT_LANGUAGE,
	DEFAULT_SHOW_LINE_NUMBERS,
	DEFAULT_START_LINE_NUMBER,
	LABEL_DISABLED_CLASSES,
	LABEL_ENABLED_CLASSES,
	LABEL_SIZE_CLASSES,
	REQUIRED_INDICATOR_CLASSES,
	type BadgeVariant,
	type CodeBlockSize,
	type CodeBlockVariant,
	type LabelSize
} from './typography-elements';

export type { BadgeVariant, CodeBlockSize, CodeBlockVariant, LabelSize };
export type BadgeSize = CommonSize;

export { BADGE_DEFAULT_VARIANT, BADGE_DEFAULT_SIZE };

export {
	DEFAULT_LANGUAGE,
	DEFAULT_CODE_BLOCK_VARIANT,
	DEFAULT_CODE_BLOCK_SIZE,
	DEFAULT_SHOW_LINE_NUMBERS,
	DEFAULT_START_LINE_NUMBER
};

export { DEFAULT_LABEL_SIZE, DEFAULT_LABEL_REQUIRED, DEFAULT_LABEL_DISABLED };
