export const TOKEN_DEVELOPMENT_ICON = [
	'playground',
	'playground-ai-assistant',
	'playground-ai-chat',
	'playground-ai-panel',
	'playground-animated-background',
	'playground-canvas-shell',
	'playground-code-viewer',
	'playground-component-catalog',
	'playground-component-info-card',
	'playground-component-tree',
	'playground-cta-buttons',
	'playground-device-frame',
	'playground-drawing-overlay',
	'playground-enhanced-export-panel',
	'playground-error-boundary',
	'playground-feature-grid',
	'playground-generic-code-viewer',
	'playground-hero',
	'playground-live-code-section',
	'playground-markdown-renderer',
	'playground-mission-banner',
	'playground-screenshot-selector',
	'playground-shell-header',
	'playground-shortcuts-panel',
	'playground-toast',
	'playground-tree-node'
] as const;
