import type { ContractCodeBlock as CodeBlockContract } from '$stylist/development/interface/contract/code-block';
import type { RecipeCodeDiff as CodeDiffContract } from '$stylist/development/interface/recipe/code-diff';
import type { RecipeComponentPreview as ComponentPreviewContract } from '$stylist/development/interface/recipe/component-preview';
import type { RecipeDocumentationBlock as DocumentationBlockContract } from '$stylist/development/interface/recipe/documentation-block';
import type { RecipePrivacySettings as PrivacySettingsContract } from '$stylist/development/interface/recipe/privacy-settings';
import type { RecipePlaygroundHero as PlaygroundHeroContract } from '$stylist/development/interface/recipe/playground-hero';
import type { RecipePlaygroundShellHeader as PlaygroundShellHeaderContract } from '$stylist/development/interface/recipe/playground-shell-header';
import type { RecipePlaygroundComponentCatalog as PlaygroundComponentCatalogContract } from '$stylist/development/interface/recipe/playground-component-catalog';
import type { RecipePlaygroundComponentInfoCard as PlaygroundComponentInfoCardContract } from '$stylist/development/interface/recipe/playground-component-info-card';
import type { RecipePlaygroundCodeViewer as PlaygroundCodeViewerContract } from '$stylist/development/interface/recipe/playground-code-viewer';
import type { RecipePlaygroundDeviceFrame as PlaygroundDeviceFrameContract } from '$stylist/development/interface/recipe/playground-device-frame';
import type { RecipePlaygroundToast as PlaygroundToastContract } from '$stylist/development/interface/recipe/playground-toast';
import type { RecipeDebugConsole as DebugConsoleContract } from '$stylist/development/interface/recipe/debug-console';
import type { RecipeDesignTokens as DesignTokensContract } from '$stylist/development/interface/recipe/design-tokens';
import type { RecipeComponentLibraryStats as ComponentLibraryStatsContract } from '$stylist/development/interface/recipe/component-library-stats';
import type { RecipeAtomicPrinciplesShowcase as AtomicPrinciplesShowcaseContract } from '$stylist/development/interface/recipe/atomic-principles-showcase';
import type { RecipeDevelopmentErrorBoundary as DevelopmentErrorBoundaryContract } from '$stylist/development/interface/recipe/development-error-boundary';
import type { RecipeMockDataSelector as MockDataSelectorContract } from '$stylist/development/interface/recipe/mock-data-selector';
import type { RecipePlaygroundCanvasShell as PlaygroundCanvasShellContract } from '$stylist/development/interface/recipe/playground-canvas-shell';
import type { RecipePlaygroundComponentTree as PlaygroundComponentTreeContract } from '$stylist/development/interface/recipe/playground-component-tree';
import type { RecipePlaygroundCtaButtons as PlaygroundCtaButtonsContract } from '$stylist/development/interface/recipe/playground-cta-buttons';
import type { RecipePlaygroundAnimatedBackground as PlaygroundAnimatedBackgroundContract } from '$stylist/development/interface/recipe/playground-animated-background';
import type { RecipePlaygroundMissionBanner as PlaygroundMissionBannerContract } from '$stylist/development/interface/recipe/playground-mission-banner';
import type { RecipePlaygroundScreenshotSelector as PlaygroundScreenshotSelectorContract } from '$stylist/development/interface/recipe/playground-screenshot-selector';
import type { RecipePlaygroundShortcutsPanel as PlaygroundShortcutsPanelContract } from '$stylist/development/interface/recipe/playground-shortcuts-panel';
import type { RecipePlaygroundFeatureGrid as PlaygroundFeatureGridContract } from '$stylist/development/interface/recipe/playground-feature-grid';
import type { RecipePlaygroundLiveCodeSection as PlaygroundLiveCodeSectionContract } from '$stylist/development/interface/recipe/playground-live-code-section';
import type { RecipePlaygroundMarkdownRenderer as PlaygroundMarkdownRendererContract } from '$stylist/development/interface/recipe/playground-markdown-renderer';
import type { RecipePlaygroundTreeNode as PlaygroundTreeNodeContract } from '$stylist/development/interface/recipe/playground-tree-node';
import type { RecipePlaygroundEnhancedExportPanel as PlaygroundEnhancedExportPanelContract } from '$stylist/development/interface/recipe/playground-enhanced-export-panel';
import type { RecipePlaygroundErrorBoundary as PlaygroundErrorBoundaryContract } from '$stylist/development/interface/recipe/playground-error-boundary';
import type { RecipePlaygroundGenericCodeViewer as PlaygroundGenericCodeViewerContract } from '$stylist/development/interface/recipe/playground-generic-code-viewer';
import type { RecipePlaygroundDrawingOverlay as PlaygroundDrawingOverlayContract } from '$stylist/development/interface/recipe/playground-drawing-overlay';
import type { RecipeResourceOptimizer as ResourceOptimizerContract } from '$stylist/development/interface/recipe/resource-optimizer';
import type { RecipeStylist as StylistContract } from '$stylist/development/interface/recipe/stylist';
import type { RecipePlaygroundAiAssistant as PlaygroundAiAssistantContract } from '$stylist/development/interface/recipe/playground-ai-assistant';
import type { RecipePlaygroundAiChat as PlaygroundAiChatContract } from '$stylist/development/interface/recipe/playground-ai-chat';
import type { RecipePlaygroundAiPanel as PlaygroundAiPanelContract } from '$stylist/development/interface/recipe/playground-ai-panel';
import type { RecipeAtomicPrinciplesShowcase } from '$stylist/development/interface/recipe/atomic-principles-showcase';
import type { ContractCodeBlock } from '$stylist/development/interface/contract/code-block';
import type { RecipeCodeDiff } from '$stylist/development/interface/recipe/code-diff';
import type { RecipeComponentLibraryStats } from '$stylist/development/interface/recipe/component-library-stats';
import type { RecipeComponentPreview } from '$stylist/development/interface/recipe/component-preview';
import type { RecipeDebugConsole } from '$stylist/development/interface/recipe/debug-console';
import type { RecipeDesignTokens } from '$stylist/development/interface/recipe/design-tokens';
import type { RecipeDevelopmentErrorBoundary } from '$stylist/development/interface/recipe/development-error-boundary';
import type { RecipeDocumentationBlock } from '$stylist/development/interface/recipe/documentation-block';
import type { RecipeMockDataSelector } from '$stylist/development/interface/recipe/mock-data-selector';
import type { RecipePlaygroundAiAssistant } from '$stylist/development/interface/recipe/playground-ai-assistant';
import type { RecipePlaygroundAiChat } from '$stylist/development/interface/recipe/playground-ai-chat';
import type { RecipePlaygroundAiPanel } from '$stylist/development/interface/recipe/playground-ai-panel';
import type { RecipePlaygroundAnimatedBackground } from '$stylist/development/interface/recipe/playground-animated-background';
import type { RecipePlaygroundCanvasShell } from '$stylist/development/interface/recipe/playground-canvas-shell';
import type { RecipePlaygroundCodeViewer } from '$stylist/development/interface/recipe/playground-code-viewer';
import type { RecipePlaygroundComponentCatalog } from '$stylist/development/interface/recipe/playground-component-catalog';
import type { RecipePlaygroundComponentInfoCard } from '$stylist/development/interface/recipe/playground-component-info-card';
import type { RecipePlaygroundComponentTree } from '$stylist/development/interface/recipe/playground-component-tree';
import type { RecipePlaygroundCtaButtons } from '$stylist/development/interface/recipe/playground-cta-buttons';
import type { RecipePlaygroundDeviceFrame } from '$stylist/development/interface/recipe/playground-device-frame';
import type { RecipePlaygroundDrawingOverlay } from '$stylist/development/interface/recipe/playground-drawing-overlay';
import type { RecipePlaygroundEnhancedExportPanel } from '$stylist/development/interface/recipe/playground-enhanced-export-panel';
import type { RecipePlaygroundErrorBoundary } from '$stylist/development/interface/recipe/playground-error-boundary';
import type { RecipePlaygroundFeatureGrid } from '$stylist/development/interface/recipe/playground-feature-grid';
import type { RecipePlaygroundGenericCodeViewer } from '$stylist/development/interface/recipe/playground-generic-code-viewer';
import type { RecipePlaygroundHero } from '$stylist/development/interface/recipe/playground-hero';
import type { RecipePlaygroundLiveCodeSection } from '$stylist/development/interface/recipe/playground-live-code-section';
import type { RecipePlaygroundMarkdownRenderer } from '$stylist/development/interface/recipe/playground-markdown-renderer';
import type { RecipePlaygroundMissionBanner } from '$stylist/development/interface/recipe/playground-mission-banner';
import type { RecipePlaygroundScreenshotSelector } from '$stylist/development/interface/recipe/playground-screenshot-selector';
import type { RecipePlaygroundShellHeader } from '$stylist/development/interface/recipe/playground-shell-header';
import type { RecipePlaygroundShortcutsPanel } from '$stylist/development/interface/recipe/playground-shortcuts-panel';
import type { RecipePlaygroundToast } from '$stylist/development/interface/recipe/playground-toast';
import type { RecipePlaygroundTreeNode } from '$stylist/development/interface/recipe/playground-tree-node';
import type { RecipePrivacySettings } from '$stylist/development/interface/recipe/privacy-settings';
import type { RecipeResourceOptimizer } from '$stylist/development/interface/recipe/resource-optimizer';
import type { RecipeStylist } from '$stylist/development/interface/recipe/stylist';

export interface ContractDevelopment {
	CodeBlock: ContractCodeBlock;
	RecipeCodeDiff: RecipeCodeDiff;
	RecipeComponentPreview: RecipeComponentPreview;
	RecipeDocumentationBlock: RecipeDocumentationBlock;
	RecipePrivacySettings: RecipePrivacySettings;
	RecipePlaygroundHero: RecipePlaygroundHero;
	RecipePlaygroundShellHeader: RecipePlaygroundShellHeader;
	RecipePlaygroundComponentCatalog: RecipePlaygroundComponentCatalog;
	RecipePlaygroundComponentInfoCard: RecipePlaygroundComponentInfoCard;
	RecipePlaygroundCodeViewer: RecipePlaygroundCodeViewer;
	RecipePlaygroundDeviceFrame: RecipePlaygroundDeviceFrame;
	RecipePlaygroundToast: RecipePlaygroundToast;
	RecipeDebugConsole: RecipeDebugConsole;
	RecipeDesignTokens: RecipeDesignTokens;
	RecipeComponentLibraryStats: RecipeComponentLibraryStats;
	RecipeAtomicPrinciplesShowcase: RecipeAtomicPrinciplesShowcase;
	RecipeDevelopmentErrorBoundary: RecipeDevelopmentErrorBoundary;
	MockDataSelector: RecipeMockDataSelector;
	RecipePlaygroundCanvasShell: RecipePlaygroundCanvasShell;
	RecipePlaygroundComponentTree: RecipePlaygroundComponentTree;
	RecipePlaygroundCtaButtons: RecipePlaygroundCtaButtons;
	RecipePlaygroundAnimatedBackground: RecipePlaygroundAnimatedBackground;
	RecipePlaygroundMissionBanner: RecipePlaygroundMissionBanner;
	RecipePlaygroundScreenshotSelector: RecipePlaygroundScreenshotSelector;
	RecipePlaygroundShortcutsPanel: RecipePlaygroundShortcutsPanel;
	RecipePlaygroundFeatureGrid: RecipePlaygroundFeatureGrid;
	RecipePlaygroundLiveCodeSection: RecipePlaygroundLiveCodeSection;
	RecipePlaygroundMarkdownRenderer: RecipePlaygroundMarkdownRenderer;
	RecipePlaygroundTreeNode: RecipePlaygroundTreeNode;
	RecipePlaygroundEnhancedExportPanel: RecipePlaygroundEnhancedExportPanel;
	RecipePlaygroundErrorBoundary: RecipePlaygroundErrorBoundary;
	RecipePlaygroundGenericCodeViewer: RecipePlaygroundGenericCodeViewer;
	RecipePlaygroundDrawingOverlay: RecipePlaygroundDrawingOverlay;
	RecipeResourceOptimizer: RecipeResourceOptimizer;
	RecipeStylist: RecipeStylist;
	RecipePlaygroundAiAssistant: RecipePlaygroundAiAssistant;
	RecipePlaygroundAiChat: RecipePlaygroundAiChat;
	RecipePlaygroundAiPanel: RecipePlaygroundAiPanel;
}
