import type { InformationHTMLAttributes } from '$stylist/information/type/struct/item';
import type { ChildrenHtmlAttributes } from '$stylist/layout/type/struct/children';
import type { BillingSummaryContract, BillingItemContract } from '$stylist/commerce/interface/component/billing-summary/contract';
import type { OrderConfirmationContract } from '$stylist/commerce/interface/component/order-confirmation/contract';
import type { PriceAlertContract } from '$stylist/commerce/interface/component/price-alert/contract';
import type { ProductSortingContract } from '$stylist/commerce/interface/component/product-sorting/contract';
import type { QuoteRequestContract } from '$stylist/commerce/interface/component/quote-request/contract';
import type { ProductGalleryContract } from '$stylist/commerce/interface/component/product-gallery/contract';
import type { ProductCarouselContract } from '$stylist/commerce/interface/component/product-carousel/contract';
import type { ProductComparisonContract } from '$stylist/commerce/interface/component/product-comparison/contract';
import type { CurrencyConverterContract } from '$stylist/commerce/interface/component/currency-converter/contract';
import type { DiscountApplierContract } from '$stylist/commerce/interface/component/discount-applier/contract';
import type { InventoryTrackerContract } from '$stylist/commerce/interface/component/inventory-tracker/contract';
import type { OrderHistoryContract } from '$stylist/commerce/interface/component/order-history/contract';
import type { OrderTrackingContract } from '$stylist/commerce/interface/component/order-tracking/contract';
import type { ShippingCalculatorContract } from '$stylist/commerce/interface/component/shipping-calculator/contract';
import type { ShippingInfoContract } from '$stylist/commerce/interface/component/shipping-info/contract';
import type { SubscriptionManagerContract } from '$stylist/commerce/interface/component/subscription-manager/contract';
import type { TaxCalculatorContract } from '$stylist/commerce/interface/component/tax-calculator/contract';
import type { UpsellContract } from '$stylist/commerce/interface/component/upsell/contract';
import type { WarrantyInfoContract } from '$stylist/commerce/interface/component/warranty-info/contract';
import type { ReturnPolicyContract } from '$stylist/commerce/interface/component/return-policy/contract';
import type { RFQFormContract } from '$stylist/commerce/interface/component/rfqform/contract';
import type { ProductCardExtendedContract } from '$stylist/commerce/interface/component/product-card-extended/contract';
import type { ProductCatalogContract } from '$stylist/commerce/interface/component/product-catalog/contract';
import type { ProductReviewsContract } from '$stylist/commerce/interface/component/product-reviews/contract';
import type { ProductTourContract } from '$stylist/commerce/interface/component/product-tour/contract';
import type { ProductAvailabilityContract } from '$stylist/commerce/interface/component/product-availability/contract';
import type { ProductWishlistContract } from '$stylist/commerce/interface/component/product-wishlist/contract';
import type { PriceFilterContract } from '$stylist/commerce/interface/component/price-filter/contract';
import type { PriceHistoryContract } from '$stylist/commerce/interface/component/price-history/contract';
import type { PriceMatchContract } from '$stylist/commerce/interface/component/price-match/contract';
import type { PricingTableContract } from '$stylist/commerce/interface/component/pricing-table/contract';
import type { ProductCardContract } from '$stylist/commerce/interface/component/product-card/contract';
import type { ProductComparisonTableContract } from '$stylist/commerce/interface/component/product-comparison-table/contract';
import type { ProductSearchContract } from '$stylist/commerce/interface/component/product-search/contract';
import type { WishlistButtonContract } from '$stylist/commerce/interface/component/wishlist-button/contract';
import type { ProductDemoContract } from '$stylist/commerce/interface/component/product-demo/contract';
import type { ProductRecommendationContract } from '$stylist/commerce/interface/component/product-recommendation/contract';

export interface MapCommerceContract {
	BillingSummary: BillingSummaryContract;
	OrderConfirmation: OrderConfirmationContract;
	PriceAlert: PriceAlertContract;
	ProductSorting: ProductSortingContract;
	QuoteRequest: QuoteRequestContract;
	ProductGallery: ProductGalleryContract;
	ProductCarousel: ProductCarouselContract;
	ProductComparison: ProductComparisonContract;
	CurrencyConverter: CurrencyConverterContract;
	DiscountApplier: DiscountApplierContract;
	InventoryTracker: InventoryTrackerContract;
	OrderHistory: OrderHistoryContract;
	OrderTracking: OrderTrackingContract;
	ShippingCalculator: ShippingCalculatorContract;
	ShippingInfo: ShippingInfoContract;
	SubscriptionManager: SubscriptionManagerContract;
	TaxCalculator: TaxCalculatorContract;
	Upsell: UpsellContract;
	WarrantyInfo: WarrantyInfoContract;
	ReturnPolicy: ReturnPolicyContract;
	RFQForm: RFQFormContract;
	ProductCardExtended: ProductCardExtendedContract;
	ProductCatalog: ProductCatalogContract;
	ProductReviews: ProductReviewsContract;
	ProductTour: ProductTourContract;
	ProductAvailability: ProductAvailabilityContract;
	ProductWishlist: ProductWishlistContract;
	PriceFilter: PriceFilterContract;
	PriceHistory: PriceHistoryContract;
	PriceMatch: PriceMatchContract;
	PricingTable: PricingTableContract;
	ProductCard: ProductCardContract;
	ProductComparisonTable: ProductComparisonTableContract;
	ProductSearch: ProductSearchContract;
	WishlistButton: WishlistButtonContract;
	ProductDemo: ProductDemoContract;
	ProductRecommendation: ProductRecommendationContract;
}
