import { DOMAIN_SCREEN } from '$stylist/domain/const/value/domain-screen';

export const DOMAIN_SCREEN_VALUES = [
	DOMAIN_SCREEN.LANDING,
	DOMAIN_SCREEN.DOMAIN,
	DOMAIN_SCREEN.WORKSPACE,
	DOMAIN_SCREEN.BUILDER,
	DOMAIN_SCREEN.BACKLOG,
	DOMAIN_SCREEN.DASHBOARD,
	DOMAIN_SCREEN.DIAGNOSTICS
] as const;
