import type { AnnouncementBannerContract } from '$stylist/media/interface/component/announcement-banner/contract';
import type { AudioPlayerContract } from '$stylist/media/interface/component/audio-player/contract';
import type { AudioSliderContract } from '$stylist/media/interface/component/audio-slider/contract';
import type { AudioVisualizerContract } from '$stylist/media/interface/component/audio-visualizer/contract';
import type { AvatarContract } from '$stylist/media/interface/component/avatar/contract';
import type { AvatarGroupContract } from '$stylist/media/interface/component/avatar-group/contract';
import type { CanvasImageEditorContract } from '$stylist/media/interface/component/canvas-image-editor/contract';
import type { CountryFlagContract } from '$stylist/media/interface/component/country-flag/contract';
import type { FaviconContract } from '$stylist/media/interface/component/favicon/contract';
import type { IconContract } from '$stylist/media/interface/component/icon/contract';
import type { ImageContract } from '$stylist/media/interface/component/image/contract';
import type { ImageGalleryContract } from '$stylist/media/interface/component/image-gallery/contract';
import type { ImageWithCaptionContract } from '$stylist/media/interface/component/image-with-caption/contract';
import type { MediaLibraryContract } from '$stylist/media/interface/component/media-library/contract';
import type { NodeIconContract } from '$stylist/media/interface/component/node-icon/contract';
import type { PromoBannerContract } from '$stylist/media/interface/component/promo-banner/contract';
import type { SvgContract } from '$stylist/media/interface/component/svg/contract';
import type { TeamAvatarStackContract } from '$stylist/media/interface/component/team-avatar-stack/contract';
import type { VideoPlayerContract } from '$stylist/media/interface/component/video-player/contract';

export interface MapMediaContract {
	AnnouncementBanner: AnnouncementBannerContract;
	AudioPlayer: AudioPlayerContract;
	AudioSlider: AudioSliderContract;
	AudioVisualizer: AudioVisualizerContract;
	Avatar: AvatarContract;
	AvatarGroup: AvatarGroupContract;
	CanvasImageEditor: CanvasImageEditorContract;
	CountryFlag: CountryFlagContract;
	Favicon: FaviconContract;
	Icon: IconContract;
	Image: ImageContract;
	ImageGallery: ImageGalleryContract;
	ImageWithCaption: ImageWithCaptionContract;
	MediaLibrary: MediaLibraryContract;
	NodeIcon: NodeIconContract;
	PromoBanner: PromoBannerContract;
	Svg: SvgContract;
	TeamAvatarStack: TeamAvatarStackContract;
	VideoPlayer: VideoPlayerContract;
}
