import type { SlotAccordion as IAccordionProps } from '$stylist/control/interface/slot/accordion';
import type { RecipeAdvancedAccordionProps as IAdvancedAccordionProps } from '$stylist/control/interface/recipe/advanced-accordion-props';
import type { ThemeAdvancedColorPickerRecipe } from '$stylist/color/interface/recipe/advanced-color-picker';
import type { SlotAdvancedPasswordInput as IAdvancedPasswordInputProps } from '$stylist/input/interface/slot/advanced-password-input';
import type { SlotBurgerMenu as BurgerMenuProps } from '$stylist/control/interface/slot/burger-menu';
import type { SlotButtonElement as ButtonElementProps } from '$stylist/control/interface/slot/button-element';
import type { SlotChatStatusIndicator as ChatStatusIndicatorProps } from '$stylist/communication/interface/slot/chat-status-indicator';
import type { SlotClick as ClickProps } from '$stylist/control/interface/slot/click';
import type { SlotDialog as DialogProps } from '$stylist/navigation/interface/slot/dialog';
import type { SlotModal as ModalProps } from '$stylist/navigation/interface/slot/modal';
import type { SlotDragAndDrop as DragAndDropProps } from '$stylist/control/interface/slot/drag-and-drop';
import type { SlotDropdownMenu as IDropdownMenuProps } from '$stylist/control/interface/slot/dropdown-menu';
import type { SlotErrorBoundary as IErrorBoundaryProps } from '$stylist/notification/interface/slot/error-boundary';
import type { SlotErrorMessage as ErrorMessageProps } from '$stylist/notification/interface/slot/error-message-error-message';
import type { SlotFeatureToggle as FeatureToggleProps } from '$stylist/management/interface/slot/feature-toggle';
import type { ThemeIconPickerRecipe } from '$stylist/media/interface/recipe/icon-picker';
import type { SlotLazyLoader as LazyLoaderProps } from '$stylist/notification/interface/slot/lazy-loader';
import type { SlotLoadingBoundary as LoadingBoundaryProps } from '$stylist/notification/interface/slot/loading-boundary';
import type { SlotResponseViewer as ResponseViewerProps } from '$stylist/notification/interface/slot/response-viewer';
import type { SlotLocaleSwitcher as LocaleSwitcherProps } from '$stylist/localization/interface/slot/locale-switcher';
import type { SlotMenuItem as MenuItemProps } from '$stylist/control/interface/slot/menu-item';
import type { SlotMultiSelect as MultiSelectProps } from '$stylist/control/interface/slot/multi-select';
import type { SlotNumberInput as INumberInputProps } from '$stylist/input/interface/slot/number-input';
import type { SlotLoadingOverlay as ILoadingOverlayProps } from '$stylist/notification/interface/slot/loading-overlay';
import type { SlotPagination as PaginationProps } from '$stylist/navigation/interface/slot/pagination';
import type { SlotPhoneNumberInput as IPhoneNumberInputProps } from '$stylist/input/interface/slot/phone-number-input';
import type { SlotQuantitySelector as IQuantitySelectorProps } from '$stylist/control/interface/slot/quantity-selector';
import type { SlotRangeInput as RangeInputProps } from '$stylist/input/interface/slot/range-input';
import type { SlotRangeSlider as IRangeSliderProps } from '$stylist/input/interface/slot/range-slider';
import type { SlotRating as IRatingProps } from '$stylist/social/interface/slot/rating';
import type { SlotReactionPicker as IReactionPickerProps } from '$stylist/input/interface/slot/reaction-picker';
import type { SlotSearchBar as ISearchBarProps } from '$stylist/control/interface/slot/search-bar';
import type { SlotSelect as ISelectProps } from '$stylist/control/interface/slot/select';
import type { SlotSortableTableHeader as SortableTableHeaderProps } from '$stylist/control/interface/slot/sortable-table-header';
import type { SlotSwitch as SwitchProps } from '$stylist/control/interface/slot/switch';
import type { SlotSwitchWithLabel as ISwitchWithLabelProps } from '$stylist/control/interface/slot/switch-with-label';
import type { SlotTabGroup as ITabGroupProps } from '$stylist/control/interface/slot/tab-group';
import type { SlotTabs as TabsProps } from '$stylist/control/interface/slot/tabs';
import type { SlotTagInput as TagInputProps } from '$stylist/input/interface/slot/tag-input';
import type { SlotTooltip as TooltipProps } from '$stylist/control/interface/slot/tooltip';
import type { SlotTransformation as TransformationProps } from '$stylist/animation/interface/slot/transformation';
import type { SlotTranslationEditor as TranslationEditorProps } from '$stylist/localization/interface/slot/translation-editor';
import type { SlotZoomControls as ZoomControlsProps } from '$stylist/control/interface/slot/zoom-controls';
import type { SlotTransformation } from '$stylist/animation/interface/slot/transformation';
import type { SlotChatStatusIndicator } from '$stylist/communication/interface/slot/chat-status-indicator';
import type { SlotAccordion } from '$stylist/control/interface/slot/accordion';
import type { RecipeAdvancedAccordionProps } from '$stylist/control/interface/recipe/advanced-accordion-props';
import type { SlotBurgerMenu } from '$stylist/control/interface/slot/burger-menu';
import type { SlotButtonElement } from '$stylist/control/interface/slot/button-element';
import type { SlotClickable } from '$stylist/interaction/interface/slot/clickable';
import type { SlotDragAndDrop } from '$stylist/control/interface/slot/drag-and-drop';
import type { SlotDropdownMenu } from '$stylist/control/interface/slot/dropdown-menu';
import type { SlotMenuItem } from '$stylist/control/interface/slot/menu-item';
import type { SlotMultiSelect } from '$stylist/control/interface/slot/multi-select';
import type { SlotQuantitySelector } from '$stylist/control/interface/slot/quantity-selector';
import type { SlotSearchBar } from '$stylist/control/interface/slot/search-bar';
import type { SlotSelect } from '$stylist/control/interface/slot/select';
import type { SlotSortableTableHeader } from '$stylist/control/interface/slot/sortable-table-header';
import type { SlotSwitchWithLabel } from '$stylist/control/interface/slot/switch-with-label';
import type { SlotSwitch } from '$stylist/control/interface/slot/switch';
import type { SlotTabGroup } from '$stylist/control/interface/slot/tab-group';
import type { SlotTabs } from '$stylist/control/interface/slot/tabs';
import type { SlotTooltip } from '$stylist/control/interface/slot/tooltip';
import type { SlotZoomControls } from '$stylist/control/interface/slot/zoom-controls';
import type { SlotAdvancedPasswordInput } from '$stylist/input/interface/slot/advanced-password-input';
import type { SlotNumberInput } from '$stylist/input/interface/slot/number-input';
import type { SlotPhoneNumberInput } from '$stylist/input/interface/slot/phone-number-input';
import type { SlotRangeInput } from '$stylist/input/interface/slot/range-input';
import type { SlotRangeSlider } from '$stylist/input/interface/slot/range-slider';
import type { SlotReactionPicker } from '$stylist/input/interface/slot/reaction-picker';
import type { SlotTagInput } from '$stylist/input/interface/slot/tag-input';
import type { SlotLocaleSwitcher } from '$stylist/localization/interface/slot/locale-switcher';
import type { SlotTranslationEditor } from '$stylist/localization/interface/slot/translation-editor';
import type { SlotFeatureToggle } from '$stylist/management/interface/slot/feature-toggle';
import type { SlotDialog } from '$stylist/navigation/interface/slot/dialog';
import type { SlotModal } from '$stylist/navigation/interface/slot/modal';
import type { SlotPagination } from '$stylist/navigation/interface/slot/pagination';
import type { SlotErrorBoundary } from '$stylist/notification/interface/slot/error-boundary';
import type { SlotErrorMessage } from '$stylist/notification/interface/slot/error-message';
import type { SlotLazyLoader } from '$stylist/notification/interface/slot/lazy-loader';
import type { SlotLoadingBoundary } from '$stylist/notification/interface/slot/loading-boundary';
import type { SlotResponseViewer } from '$stylist/notification/interface/slot/response-viewer';
import type { SlotLoadingOverlay } from '$stylist/notification/interface/slot/loading-overlay';
import type { SlotRating } from '$stylist/social/interface/slot/rating';

export interface ContractMapInteraction {
	Accordion: SlotAccordion;
	AdvancedAccordion: RecipeAdvancedAccordionProps;
	AdvancedColorPicker: ThemeAdvancedColorPickerRecipe;
	AdvancedPasswordInput: SlotAdvancedPasswordInput;
	BurgerMenu: SlotBurgerMenu;
	Button: SlotButtonElement;
	ChatStatusIndicator: SlotChatStatusIndicator;
	Click: SlotClickable;
	Dialog: SlotDialog;
	Modal: SlotModal;
	DragAndDrop: SlotDragAndDrop;
	DropdownMenu: SlotDropdownMenu;
	ErrorBoundary: SlotErrorBoundary;
	ErrorMessage: SlotErrorMessage;
	FeatureToggle: SlotFeatureToggle;
	IconPicker: ThemeIconPickerRecipe;
	LazyLoader: SlotLazyLoader;
	LoadingBoundary: SlotLoadingBoundary;
	ResponseViewer: SlotResponseViewer;
	LocaleSwitcher: SlotLocaleSwitcher;
	MenuItem: SlotMenuItem;
	MultiSelect: SlotMultiSelect;
	NumberInput: SlotNumberInput;
	LoadingOverlay: SlotLoadingOverlay;
	Pagination: SlotPagination;
	PhoneNumberInput: SlotPhoneNumberInput;
	QuantitySelector: SlotQuantitySelector;
	RangeInput: SlotRangeInput;
	RangeSlider: SlotRangeSlider;
	Rating: SlotRating;
	ReactionPicker: SlotReactionPicker;
	SearchBar: SlotSearchBar;
	Selector: SlotSelect;
	SortableTableHeader: SlotSortableTableHeader;
	Switch: SlotSwitch;
	SwitchWithLabel: SlotSwitchWithLabel;
	TabGroup: SlotTabGroup;
	Tabs: SlotTabs;
	TagInput: SlotTagInput;
	Tooltip: SlotTooltip;
	Transformation: SlotTransformation;
	TranslationEditor: SlotTranslationEditor;
	ZoomControls: SlotZoomControls;
}
