import type { SlotSvgName } from '$stylist/svg/interface/slot/svg-name';
import { ICON_AI }           from '$stylist/svg/const/value/ai';
import { ICON_AUDIO }        from '$stylist/svg/const/value/audio';
import { ICON_ANIMATION }    from '$stylist/svg/const/value/animation';
import { ICON_ARCHITECTURE } from '$stylist/svg/const/value/architecture';
import { ICON_AUTH }         from '$stylist/svg/const/value/auth';
import { ICON_BUTTON }       from '$stylist/svg/const/value/button';
import { ICON_CALENDAR }     from '$stylist/svg/const/value/calendar';
import { ICON_CANVAS }       from '$stylist/svg/const/value/canvas';
import { ICON_CHART }        from '$stylist/svg/const/value/chart';
import { ICON_CHAT }         from '$stylist/svg/const/value/chat';
import { ICON_COMMERCE }     from '$stylist/svg/const/value/commerce';
import { ICON_CONTROL }      from '$stylist/svg/const/value/control';
import { ICON_DEVELOPMENT }  from '$stylist/svg/const/value/development';
import { ICON_DIALOGS }      from '$stylist/svg/const/value/dialogs';
import { ICON_DOMAIN }       from '$stylist/svg/const/value/domain';
import { ICON_ERD }          from '$stylist/svg/const/value/erd';
import { ICON_FILE }         from '$stylist/svg/const/value/file';
import { ICON_FORM }         from '$stylist/svg/const/value/form';
import { ICON_GEO }          from '$stylist/svg/const/value/geo';
import { ICON_GRAPH }        from '$stylist/svg/const/value/graph';
import { ICON_IMAGE }        from '$stylist/svg/const/value/image';
import { ICON_INPUT }        from '$stylist/svg/const/value/input';
import { ICON_IDEF_ZERO }    from '$stylist/svg/const/value/idef-zero';
import { ICON_LANDING }      from '$stylist/svg/const/value/landing';
import { ICON_LAYOUT }       from '$stylist/svg/const/value/layout';
import { ICON_LIST }         from '$stylist/svg/const/value/list';
import { ICON_LOCALIZATION } from '$stylist/svg/const/value/localization';
import { ICON_MANAGEMENT }   from '$stylist/svg/const/value/management';
import { ICON_MARKETING }    from '$stylist/svg/const/value/marketing';
import { ICON_NAVIGATION }   from '$stylist/svg/const/value/navigation';
import { ICON_NOTIFICATION } from '$stylist/svg/const/value/notification';
import { ICON_PORTFOLIO }    from '$stylist/svg/const/value/portfolio';
import { ICON_PRESENTATION } from '$stylist/svg/const/value/presentation';
import { ICON_PRODUCT }      from '$stylist/svg/const/value/product';
import { ICON_SCIENCE }      from '$stylist/svg/const/value/science';
import { ICON_SEARCH }       from '$stylist/svg/const/value/search';
import { ICON_SERVER }       from '$stylist/svg/const/value/server';
import { ICON_SOCIAL }       from '$stylist/svg/const/value/social';
import { ICON_SVG }          from '$stylist/svg/const/value/svg';
import { ICON_TABLE }        from '$stylist/svg/const/value/table';
import { ICON_THEME }        from '$stylist/svg/const/value/theme';
import { ICON_TOKEN }        from '$stylist/svg/const/value/token';
import { ICON_TREES }        from '$stylist/svg/const/value/trees';
import { ICON_TYPOGRAPHY }   from '$stylist/svg/const/value/typography';
import { ICON_USER }         from '$stylist/svg/const/value/user';
import { ICON_VIDEO }        from '$stylist/svg/const/value/video';
import { ICON_WBD }          from '$stylist/svg/const/value/wbd';
import { ICON_WORKSPACE }    from '$stylist/svg/const/value/workspace';

export const DOMAIN_MENU_ICONS = [
	{ name: 'ai',           svg: ICON_AI },
	{ name: 'audio',        svg: ICON_AUDIO },
	{ name: 'animation',    svg: ICON_ANIMATION },
	{ name: 'architecture', svg: ICON_ARCHITECTURE },
	{ name: 'auth',         svg: ICON_AUTH },
	{ name: 'button',       svg: ICON_BUTTON },
	{ name: 'calendar',     svg: ICON_CALENDAR },
	{ name: 'canvas',       svg: ICON_CANVAS },
	{ name: 'chart',        svg: ICON_CHART },
	{ name: 'chat',         svg: ICON_CHAT },
	{ name: 'commerce',     svg: ICON_COMMERCE },
	{ name: 'control',      svg: ICON_CONTROL },
	{ name: 'development',  svg: ICON_DEVELOPMENT },
	{ name: 'dialog',       svg: ICON_DIALOGS },
	{ name: 'domain',       svg: ICON_DOMAIN },
	{ name: 'erd',          svg: ICON_ERD },
	{ name: 'file',         svg: ICON_FILE },
	{ name: 'form',         svg: ICON_FORM },
	{ name: 'geo',          svg: ICON_GEO },
	{ name: 'graph',        svg: ICON_GRAPH },
	{ name: 'idef-zero',    svg: ICON_IDEF_ZERO },
	{ name: 'image',        svg: ICON_IMAGE },
	{ name: 'input',        svg: ICON_INPUT },
	{ name: 'landing',      svg: ICON_LANDING },
	{ name: 'layout',       svg: ICON_LAYOUT },
	{ name: 'list',         svg: ICON_LIST },
	{ name: 'localization', svg: ICON_LOCALIZATION },
	{ name: 'management',   svg: ICON_MANAGEMENT },
	{ name: 'marketing',    svg: ICON_MARKETING },
	{ name: 'navigation',   svg: ICON_NAVIGATION },
	{ name: 'notification', svg: ICON_NOTIFICATION },
	{ name: 'portfolio',    svg: ICON_PORTFOLIO },
	{ name: 'presentation', svg: ICON_PRESENTATION },
	{ name: 'product',      svg: ICON_PRODUCT },
	{ name: 'science',      svg: ICON_SCIENCE },
	{ name: 'search',       svg: ICON_SEARCH },
	{ name: 'server',       svg: ICON_SERVER },
	{ name: 'social',       svg: ICON_SOCIAL },
	{ name: 'svg',          svg: ICON_SVG },
	{ name: 'table',        svg: ICON_TABLE },
	{ name: 'theme',        svg: ICON_THEME },
	{ name: 'token',        svg: ICON_TOKEN },
	{ name: 'tree',         svg: ICON_TREES },
	{ name: 'typography',   svg: ICON_TYPOGRAPHY },
	{ name: 'user',         svg: ICON_USER },
	{ name: 'video',        svg: ICON_VIDEO },
	{ name: 'wbd',          svg: ICON_WBD },
	{ name: 'webgl',        svg: ICON_CANVAS },
	{ name: 'workspace',    svg: ICON_WORKSPACE }
] as const satisfies readonly SlotSvgName[];

export const DOMAIN_COUNT = DOMAIN_MENU_ICONS.length;
